---
pagetitle: "general"
---

```{r exp_2_1}
# Filter and factor
dat_exp_2 <- dat_exp_filt %>%
  dplyr::filter(version == "2a" & !is.na(vot)) %>%
  mutate(across(.cols = c("participant", "stim", "type",
                          "cond_sim", "cond_var"),
                as.factor),
         trial_cent = scale(trial)[,1],
         vot_cent = scale(vot)[,1],
         freq_cent = scale(FreqZipfUS)[,1])

# Add contrasts
contrasts(dat_exp_2$cond_sim) <- contrast_sim
contrasts(dat_exp_2$cond_var) <- contrast_var
contrasts(dat_exp_2$type) <- contrast_type
```

```{r exp_2_2}
# Run
exp_acc_2 <- glmer(resp_acc ~ cond_var*cond_sim*type + 
                     trial_cent + freq_cent + vot_cent +
                     (1|stim) + (cond_var:cond_sim + cond_var|participant),
                   data = dat_exp_2,
                   family = binomial,
                   control = glmerControl(optimizer = "bobyqa"))

# Model comparison
exp_acc_2_comp <- Anova(exp_acc_2, test = "Chi", type = "III")

# Pull
exp_acc_2_comp_2_form <- mod_comp(exp_acc_2_comp, "cond_var:type")
```

```{r exp_2_3a, warning = FALSE, message = FALSE}
# Means for Variability x Type
exp_acc_2_means_simple <- emmeans(exp_acc_2, ~ cond_var*type)

# Format
exp_acc_2_means_simple_form <- exp_acc_2_means_simple %>%
  summary(type = "response") %>%
  mutate(report = sprintf("*M* = %.2f, 95%% CI [%.2f, %.2f]", 
                          prob, asymp.LCL, asymp.UCL))

# Contrasts
exp_acc_2_cont_simple <- pairs(exp_acc_2_means_simple, 
                            by = "type", adjust = "hommel") %>%
  data.frame() %>%
  dplyr::filter(`p.value` <= .05)

# Means for three-way interaction
exp_acc_2_means <- emmeans(exp_acc_2, ~ cond_sim*cond_var*type)

# Format
exp_acc_2_means_form <- exp_acc_2_means %>% 
  summary(type = "response") %>%
  left_join(tab_factor, by = c("cond_sim", "cond_var")) %>%
  left_join(tab_type, by = "type")

# Contrasts by Variability
exp_acc_2_cont_var <- pairs(exp_acc_2_means, 
                             by = c("type", "cond_var"), 
                             adj = "hommel") %>%
  data.frame() %>%
  dplyr::filter(`p.value` <= .05)

# Contrasts by Similarity
exp_acc_2_cont_sim <- pairs(exp_acc_2_means, 
                             by = c("type", "cond_sim"), 
                             adj = "hommel") %>%
  data.frame() %>%
  dplyr::filter(`p.value` <= .05)
```

```{r exp_2_3b}
# Variability x Type
exp_acc_2_means_simple_var_non <- exp_acc_2_means_simple_form %>%
  dplyr::filter(cond_var == "variant" & type == "nonword") %>%
  pull(report)
exp_acc_2_means_simple_invar_non <- exp_acc_2_means_simple_form %>%
  dplyr::filter(cond_var == "invariant" & type == "nonword") %>%
  pull(report)
exp_acc_2_comp_simple_non <- pair_comp(exp_acc_2_cont_simple, "invariant - variant")
```

```{r exp_2_4}
# Filter and factor
dat_exp_2_rt <- dat_exp_rt %>%
  left_join(tab_factor, by = c("cond_var", "cond_sim")) %>%
  left_join(tab_type, by = c("type")) %>%
  dplyr::filter(version == "2a" & !is.na(vot)) %>%
  mutate(across(.cols = c("participant", "stim", "type",
                          "cond_sim", "cond_var"),
                as.factor),
         trial_cent = scale(trial)[,1],
         vot_cent = scale(vot)[,1],
         freq_cent = scale(FreqZipfUS)[,1])

# Add contrasts
contrasts(dat_exp_2_rt$cond_sim) <- contrast_sim
contrasts(dat_exp_2_rt$cond_var) <- contrast_var
contrasts(dat_exp_2_rt$type) <- contrast_type
```

```{r exp_2_5}
# Run
exp_rt_2 <- lmer(inv_rt ~ cond_var*cond_sim*type + 
                   trial_cent + freq_cent + vot_cent +
                   (1|stim) + (1|participant),
                 data = dat_exp_2_rt)

# Model comparison
exp_rt_2_comp <- Anova(exp_rt_2, test = "Chi", type = "III")

# Format
exp_rt_2_comp_3_form <- mod_comp(exp_rt_2_comp, "cond_var:cond_sim:type")
exp_rt_2_comp_2_form <- mod_comp(exp_rt_2_comp, "cond_sim:type")
```

```{r exp_2_6, message = FALSE, warning = FALSE}
# Means
exp_rt_2_means <- emmeans(exp_rt_2, ~ cond_sim*cond_var*type)

# Format
exp_rt_2_means_form <- exp_rt_2_means %>%
  apa_rt() %>%
  left_join(tab_factor, by = c("cond_sim", "cond_var")) %>%
  left_join(tab_type, by = "type")

# Contrasts by Variability
exp_rt_2_cont_var <- pairs(exp_rt_2_means, 
                             by = c("type", "cond_var"), 
                             adj = "hommel") %>%
  data.frame() %>%
  dplyr::filter(`p.value` <= .05)

# Contrasts by Similarity
exp_rt_2_cont_sim <- pairs(exp_rt_2_means, 
                             by = c("type", "cond_sim"), 
                             adj = "hommel") %>%
  data.frame() %>%
  dplyr::filter(`p.value` <= .05)
```

```{r exp_2_7}
# Get average accuracy
dat_exp_2_acc <- dat_exp_2 %>%
  group_by(participant, cond_var, cond_sim, cond_exp, type) %>% 
  summarise(mean_acc = mean(resp_acc), .groups = "keep") %>%
  left_join(tab_factor, by = c("cond_var", "cond_sim")) %>%
  left_join(tab_type, by = c("type"))

# Get average RT
dat_exp_2_sum <- dat_exp_2_rt %>%
  group_by(participant, cond_var, cond_sim, cond_exp, type) %>% 
  summarise(mean_rt = mean(real_rt), .groups = "keep") %>%
  left_join(dat_exp_2_acc,
            by = join_by(participant, cond_var, cond_sim, cond_exp, type))
```

```{r exp_2_8, include = FALSE}
# Plot
plot_exp_2_acc_var <- ggplot() +
  geom_boxplot(data = dat_exp_2_acc, 
               aes(x = cond_var_fac, y = mean_acc, 
                   color = cond_exp_fac, fill = cond_exp_fac),
               size = g_line, alpha = alpha_lev) +
  geom_point(data = exp_acc_2_means_form,
             aes(x = cond_var_fac, y = prob, group = cond_sim_fac), 
             position = position_dodge(width = g_dodge),
             color = "black", size = g_point*1.25) +
  geom_errorbar(data = exp_acc_2_means_form,
             aes(x = cond_var_fac, group = cond_sim_fac,
                 ymin = `asymp.LCL`, ymax = `asymp.UCL`), 
             position = position_dodge(width = g_dodge),
             color = "black", width = 0.25, size = g_line) +
  facet_grid(~ type_fac) + 
  scale_color_manual(values = col_exp, name = "Exposure condition") +
  scale_fill_manual(values = col_exp, name = "Exposure condition") +
  xlab("Variability") +
  ylab("Accuracy") +
  scale_y_continuous(breaks = acc_seq) +
  coord_cartesian(ylim = acc_range) +
  theme_minimal() +
  theme(text = element_text(family = font_fam, size = text_size)) +
  guides(color = "none", fill = "none")
  
# Plot
plot_exp_2_acc_sim <- ggplot() +
  geom_boxplot(data = dat_exp_2_acc, 
               aes(x = cond_sim_fac, y = mean_acc, 
                   color = cond_exp_fac, fill = cond_exp_fac),
               size = g_line, alpha = alpha_lev) +
  geom_point(data = exp_acc_2_means_form,
             aes(x = cond_sim_fac, y = prob, group = cond_var_fac), 
             position = position_dodge(width = g_dodge),
             color = "black", size = g_point*1.25) +
  geom_errorbar(data = exp_acc_2_means_form,
             aes(x = cond_sim_fac, group = cond_var_fac,
                 ymin = `asymp.LCL`, ymax = `asymp.UCL`), 
             position = position_dodge(width = g_dodge),
             color = "black", width = 0.25, size = g_line) +
  facet_grid(~ type_fac) + 
  scale_color_manual(values = col_exp, name = "Exposure condition") +
  scale_fill_manual(values = col_exp, name = "Exposure condition") +
  xlab("Similarity") +
  ylab("Accuracy") +
  scale_y_continuous(breaks = acc_seq) +
  coord_cartesian(ylim = acc_range) +
  theme_minimal() +
  theme(text = element_text(family = font_fam, size = text_size))  +
  guides(color = "none", fill = "none")
```

```{r exp_2_9, include = FALSE}
# Plot
plot_exp_2_rt_var <- ggplot() +
  geom_half_violin(data = dat_exp_2_rt, 
                   aes(x = cond_var_fac, y = real_rt, 
                       color = cond_exp_fac, fill = cond_exp_fac),
                   scale = "count", alpha = alpha_lev) + 
  geom_half_point(data = dat_exp_2_sum,
                  aes(x = cond_var_fac, y = mean_rt, color = cond_exp_fac),
                  alpha = alpha_lev) +
  geom_point(data = exp_rt_2_means_form,
             aes(x = cond_var_fac, y = rt, group = cond_sim_fac),
             position = position_dodge(width = g_dodge),
             color = "black", size = g_point*1.25) + 
  geom_errorbar(data = exp_rt_2_means_form,
                aes(x = cond_var_fac, group = cond_sim_fac,
                    ymin = low, ymax = high), 
                position = position_dodge(width = g_dodge),
                color = "black", width = 0.25, size = g_line) +
  facet_grid(~ type_fac) + 
  scale_color_manual(values = col_exp, name = "Exposure condition") +
  scale_fill_manual(values = col_exp, name = "Exposure condition") +
  xlab("Variability") +
  ylab("Reaction time (ms)") +
  scale_y_continuous(breaks = seq(750, 2550, 300)) +
  coord_cartesian(ylim = c(740, 2560)) +
  theme_minimal() +
  theme(text = element_text(family = font_fam, size = text_size))  +
  guides(color = "none")
  
# Plot
plot_exp_2_rt_sim <- ggplot() +
  geom_half_violin(data = dat_exp_2_rt, 
                   aes(x = cond_sim_fac, y = real_rt, 
                       color = cond_exp_fac, fill = cond_exp_fac),
                   scale = "count", alpha = alpha_lev) + 
  geom_half_point(data = dat_exp_2_sum,
                  aes(x = cond_sim_fac, y = mean_rt, color = cond_exp_fac),
                  alpha = alpha_lev) +
  geom_point(data = exp_rt_2_means_form,
             aes(x = cond_sim_fac, y = rt, group = cond_var_fac),
             position = position_dodge(width = g_dodge),
             color = "black", size = g_point*1.25) + 
  geom_errorbar(data = exp_rt_2_means_form,
                aes(x = cond_sim_fac, group = cond_var_fac,
                    ymin = low, ymax = high), 
                position = position_dodge(width = g_dodge),
                color = "black", width = 0.25, size = g_line) +
  facet_grid(~ type_fac) + 
  scale_color_manual(values = col_exp, name = "Exposure condition") +
  scale_fill_manual(values = col_exp, name = "Exposure condition") +
  xlab("Similarity") +
  ylab("Reaction time (ms)") +
  scale_y_continuous(breaks = seq(750, 2550, 300)) +
  coord_cartesian(ylim = c(740, 2560)) +
  theme_minimal() +
  theme(text = element_text(family = font_fam, size = text_size)) +
  guides(color = "none")
```

```{r exp_2_9_save_plot, include = FALSE}
plot_exp_2 <- plot_exp_2_acc_var + plot_exp_2_rt_var + 
  plot_exp_2_acc_sim + plot_exp_2_rt_sim +
  plot_layout(nrow = 2, axes = "collect_y", guides = "collect")

# Save plot and crop to remove white space
ggsave("outputs/plot_exp_2.png", plot_exp_2,
       width = 5600, height = 4200, unit = "px", dpi = 300)
knitr::plot_crop("outputs/plot_exp_2.png")
```

```{r test_2_1}
# Filter and factor
dat_test_2 <- dat_test_filt %>%
  dplyr::filter(version %in% c("2a", "2b")) %>%
  mutate(across(.cols = c("participant", "prime", "target", "match_type"),
                as.factor),
         trial_cent = scale(trial)[,1],
         vot_cent = scale(vot)[,1],
         freq_prime_cent = scale(FreqZipfUS_prime)[,1],
         freq_target_cent = scale(FreqZipfUS_target)[,1]) %>%
  left_join(tab_exp, by = "cond_exp")

# Add contrasts
contrasts(dat_test_2$cond_exp_fac) <- contrast_train
contrasts(dat_test_2$match_type) <- contrast_match_2
```

```{r test_2_2}
# Run
test_acc_2_train <- glmer(resp_acc ~ cond_exp_fac*match_type + 
                            trial_cent + freq_prime_cent:freq_target_cent + 
                            vot_cent +
                            (1|prime:target) + (1|participant),
                          data = dat_test_2,
                          family = binomial,
                          control = glmerControl(optimizer = "bobyqa"))

# Model comparison
test_acc_2_train_comp <- Anova(test_acc_2_train, test = "Chi", type = "III")

# Format
test_acc_2_comp_form <- mod_comp(test_acc_2_train_comp, 
                                 "cond_exp_fac:match_type")
```

```{r test_2_3a}
# Get means
test_acc_2_train_means <- emmeans(test_acc_2_train, 
                                  ~ cond_exp_fac*match_type)

# Format
test_acc_2_train_form <- test_acc_2_train_means %>% 
  summary(type = "response") %>%
  mutate(report = sprintf("*M* = %.2f, 95%% CI [%.2f, %.2f]", 
                          prob, asymp.LCL, asymp.UCL)) %>%
  left_join(tab_match, by = "match_type")

# Select contrasts
test_acc_2_train_coef <- emmeans:::pairwise.emmc(levels(test_acc_2_train_means)$cond_exp_fac)
test_acc_2_train_coef_1 <- test_acc_2_train_coef[c(1:4)]
test_acc_2_train_coef_2 <- test_acc_2_train_coef[c(5:10)]

# Run contrasts
test_acc_2_train_cont_1 <- contrast(test_acc_2_train_means, 
                                  test_acc_2_train_coef_1, 
                                  by = "match_type", 
                                  adj = "hommel")
test_acc_2_train_cont_2 <- contrast(test_acc_2_train_means, 
                                  test_acc_2_train_coef_2, 
                                  by = "match_type", 
                                  adj = "hommel") %>%
  data.frame() %>%
  dplyr::filter(`p.value` <= .05)
```

```{r test_2_3b}
# Identity
test_acc_2_train_indir_invar <- test_acc_2_train_form %>%
  dplyr::filter(cond_exp_fac == "Indirect-Invariant" & match_type == "identity") %>%
  pull(report)
test_acc_2_train_dir_var <- test_acc_2_train_form %>%
  dplyr::filter(cond_exp_fac == "Direct-Variant" & match_type == "identity") %>%
  pull(report)
test_acc_2_train_indir_var <- test_acc_2_train_form %>%
  dplyr::filter(cond_exp_fac == "Indirect-Variant" & match_type == "identity") %>%
  pull(report)
test_acc_2_train_comp_indirinvar_dirvar <- pair_comp(test_acc_2_train_cont_2,
                                                     "Direct-Variant - Indirect-Invariant")
test_acc_2_train_comp_indir_varinvar <- pair_comp(test_acc_2_train_cont_2,
                                                     "Indirect-Variant - Indirect-Invariant")
```

```{r test_2_4}
# Filter and factor
dat_test_2_rt <- dat_test_rt %>%
  dplyr::filter(version %in% c("2a", "2b")) %>%
  mutate(across(.cols = c("participant", "prime", "target", "match_type"),
                as.factor),
         trial_cent = scale(trial)[,1],
         vot_cent = scale(vot)[,1],
         freq_prime_cent = scale(FreqZipfUS_prime)[,1],
         freq_target_cent = scale(FreqZipfUS_target)[,1]) %>%
  left_join(tab_exp, by = "cond_exp")

# Add contrasts
contrasts(dat_test_2_rt$cond_exp_fac) <- contrast_train
contrasts(dat_test_2_rt$match_type) <- contrast_match_2
```

```{r test_2_5}
# Run
test_rt_2_train <- lmer(inv_rt ~ cond_exp_fac*match_type + 
                          trial_cent + freq_prime_cent:freq_target_cent + 
                          vot_cent +
                          (1|prime:target) + (1|participant),
                        data = dat_test_2_rt)

# Model comparison
test_rt_2_train_comp <- Anova(test_rt_2_train, test = "Chi", type = "III")

# Format
test_rt_2_comp_form <- mod_comp(test_rt_2_train_comp, "cond_exp_fac:match_type")
```

```{r test_2_6a, warning = FALSE, message = FALSE}
# Get means
test_rt_2_train_means <- emmeans(test_rt_2_train, 
                                 ~ cond_exp_fac*match_type)

# Format
test_rt_2_train_form <- test_rt_2_train_means %>%
  apa_rt() %>%
  left_join(tab_match, by = "match_type") %>%
  left_join(tab_exp, by = "cond_exp_fac")

# Select contrasts
test_rt_2_train_coef <- emmeans:::pairwise.emmc(levels(test_rt_2_train_means)$cond_exp_fac)
test_rt_2_train_coef <- test_rt_2_train_coef[c(1:4)]

# Run contrasts
test_rt_2_train_cont <- contrast(test_rt_2_train_means, 
                                 test_rt_2_train_coef, 
                                 by = "match_type", 
                                 adj = "hommel") %>%
  data.frame() %>%
  dplyr::filter(`p.value` <= .05) %>%
  left_join(tab_match, by = "match_type") %>%
  rowwise() %>%
  mutate(labs = labs_func(p.value))
```

```{r test_2_6b}
# Competitor
test_rt_2_train_no <- test_rt_2_train_form %>% 
  dplyr::filter(cond_exp_fac == "Test-only" & match_type == "competitor") %>%
  pull(report)
test_rt_2_train_invsim <- test_rt_2_train_form %>% 
  dplyr::filter(cond_exp_fac == "Direct-Invariant" & match_type == "competitor") %>%
  pull(report)
test_rt_2_no_invsim <- pair_comp(test_rt_2_train_cont, "Test-only - Direct-Invariant")
```

```{r test_2_7}
# Get average accuracy
dat_test_2_acc <- dat_test_2 %>%
  group_by(participant, cond_exp, match_type) %>% 
  summarise(mean_acc = mean(resp_acc), .groups = "keep") %>%
  left_join(tab_exp, by = "cond_exp") %>%
  left_join(tab_match, by = "match_type")

# Get average RT
dat_test_2_sum <- dat_test_2_rt %>%
  group_by(participant, cond_exp, match_type) %>% 
  summarise(mean_rt = mean(resp_rt), .groups = "keep") %>%
  left_join(tab_exp, by = "cond_exp") %>%
  left_join(tab_match, by = "match_type")
```

```{r test_2_8, include = FALSE}
# Plot
plot_test_2_acc <- ggplot() +
  geom_boxplot(data = dat_test_2_acc, 
               aes(x = cond_exp_fac, y = mean_acc,
                   color = cond_exp_fac, 
                   fill = cond_exp_fac),
               size = g_line*1.25, alpha = alpha_lev,
               outlier.size = g_point*1.25) +
  geom_point(data = test_acc_2_train_form,
             aes(x = cond_exp_fac, y = prob, 
                 group = match_type_fac), 
             position = position_dodge(width = g_dodge),
             color = "black", size = g_point*1.5) +
  geom_errorbar(data = test_acc_2_train_form,
             aes(x = cond_exp_fac, group = match_type_fac,
                 ymin = `asymp.LCL`, ymax = `asymp.UCL`), 
             position = position_dodge(width = g_dodge),
             color = "black", width = 0.25, size = g_line) +
  facet_grid(~ match_type_fac) +
  scale_color_manual(values = c("#A8A8A8", col_exp), name = "Exposure condition") +
  scale_fill_manual(values = c("#A8A8A8", col_exp), name = "Exposure condition") +
  xlab("Exposure condition") +
  ylab("Accuracy") +
  scale_y_continuous(breaks = seq(0, 1, 0.2)) +
  scale_x_discrete(guide = guide_axis(angle = 45)) +
  coord_cartesian(ylim = c(0, 1.01)) +
  theme_minimal() +
  theme(text = element_text(family = font_fam, size = text_size)) +
  guides(color = "none", fill = "none")
```

```{r test_2_9}
plot_test_2_rt <- ggplot() +
  geom_half_violin(data = dat_test_2_rt, 
                   aes(x = cond_exp_fac, y = resp_rt, 
                       color = cond_exp_fac, fill = cond_exp_fac),
                   scale = "count", alpha = alpha_lev) + 
  geom_half_point(data = dat_test_2_sum,
                  aes(x = cond_exp_fac, y = mean_rt, 
                      color = cond_exp_fac),
                  alpha = alpha_lev, size = g_point*1.25) +
  geom_point(data = test_rt_2_train_form,
             aes(x = cond_exp_fac, y = rt,
                 group = cond_exp_fac),
             position = position_dodge(width = g_dodge),
             color = "black", size = g_point*1.5) + 
  geom_errorbar(data = test_rt_2_train_form,
                aes(x = cond_exp_fac, 
                    group = cond_exp_fac,
                    ymin = rt_low, ymax = rt_high), 
                position = position_dodge(width = g_dodge),
                color = "black", width = 0.25, size = g_line) +
  facet_grid(~ match_type_fac) + 
  scale_color_manual(values = c("#A8A8A8", col_exp), name = "Exposure condition") +
  scale_fill_manual(values = c("#A8A8A8", col_exp), name = "Exposure condition") +
  scale_x_discrete(guide = guide_axis(angle = 45)) +
  scale_y_continuous(breaks = seq(250, 1750, 250)) +
  coord_cartesian(ylim = c(250, 1750)) +
  xlab("Exposure condition") +
  ylab("Reaction time (ms)") +
  theme_minimal() +
  theme(text = element_text(family = font_fam, size = text_size))  +
  guides(color = "none", fill = "none")
```

```{r test_2_9_save_plot, include = FALSE}
plot_test_2 <- plot_test_2_acc + plot_test_2_rt +
  plot_layout(nrow = 2, axes = "collect_x")

# Save plot and crop to remove white space
ggsave("outputs/plot_test_2.png", plot_test_2,
       width = 5600, height = 4200, unit = "px", dpi = 300)
knitr::plot_crop("outputs/plot_test_2.png")
```

```{r test_2a_4}
# Filter and factor
dat_test_2a_rt <- dat_test_rt %>%
  dplyr::filter(version == "2a") %>%
  mutate(across(.cols = c("participant", "prime", "target", "match_type",
                          "cond_sim", "cond_var"),
                as.factor),
         trial_cent = scale(trial)[,1],
         vot_cent = scale(vot)[,1],
         freq_prime_cent = scale(FreqZipfUS_prime)[,1],
         freq_target_cent = scale(FreqZipfUS_target)[,1])

# Add contrasts
contrasts(dat_test_2a_rt$cond_sim) <- contrast_sim
contrasts(dat_test_2a_rt$cond_var) <- contrast_var
contrasts(dat_test_2a_rt$match_type) <- contrast_match_2
```

```{r test_2a_5}
# Run
test_rt_2a <- lmer(inv_rt ~ cond_sim*cond_var*match_type + 
                     trial_cent + freq_prime_cent:freq_target_cent + 
                     vot_cent +
                     (1|prime:target) + (1|participant),
                   data = dat_test_2a_rt)

# Model comparison
test_rt_2a_comp <- Anova(test_rt_2a, test = "Chi", type = "III")

# Format
test_rt_2a_comp_var_form <- mod_comp(test_rt_2a_comp, "cond_var:match_type")
test_rt_2a_comp_sim_form <- mod_comp(test_rt_2a_comp, "cond_sim:match_type")
```

```{r test_2a_6, warning = FALSE, message = FALSE}
# Get means
test_rt_2a_means_var <- emmeans(test_rt_2a, ~ cond_var*match_type)
test_rt_2a_means_sim <- emmeans(test_rt_2a, ~ cond_sim*match_type)

# Run contrasts
test_rt_2a_cont_var <- pairs(test_rt_2a_means_var,
                             by = "match_type", adj = "hommel")
test_rt_2a_cont_sim <- pairs(test_rt_2a_means_sim, 
                             by = "match_type", adj = "hommel")
```

```{r test_2a_7a, warning = FALSE, message = FALSE}
# Get simple means
test_rt_2a_means <- emmeans(test_rt_2a, ~ cond_var*cond_sim*match_type)

# Format
test_rt_2a_means_form <- apa_rt(test_rt_2a_means)

# Run contrasts in Variability
test_rt_2a_cont_var_simple <- test_rt_2a_means %>%
  pairs(by = c("match_type", "cond_var"), adj = "hommel") %>%
  summary(type = "response") %>%
  data.frame() %>%
  dplyr::filter(`p.value` <= .05) %>%
  left_join(tab_match, by = "match_type") %>%
  rowwise() %>%
  mutate(labs = labs_func(p.value))

# Run contrasts in Similarity 
test_rt_2a_cont_sim_simple <- test_rt_2a_means %>%
  pairs(by = c("match_type", "cond_sim"), adj = "hommel") %>%
  summary(type = "response") %>%
  data.frame() %>%
  dplyr::filter(`p.value` <= .05) %>%
  left_join(tab_match, by = "match_type") %>%
  rowwise() %>%
  mutate(labs = labs_func(p.value))
```

```{r test_2a_7b}
# Competitor
test_rt_2a_mean_comp_dir_invar <- test_rt_2a_means_form %>%
  dplyr::filter(match_type == "competitor" & cond_sim == "direct" &
                  cond_var == "invariant") %>%
  pull(report)
test_rt_2a_mean_comp_dir_var <- test_rt_2a_means_form %>%
  dplyr::filter(match_type == "competitor" & cond_sim == "direct" &
                  cond_var == "variant") %>%
  pull(report)
test_rt_2a_comp_dir_varinvar <- pair_comp(test_rt_2a_cont_sim_simple,
                                          "invariant - variant")

# Unrelated
```

```{r explore_1}
# Load survey data
dat_survey <- read.csv("~/Mirror/dissertation/12_behavioral/data/quality/dat_survey.csv") %>%
  mutate(
    acc_lang = case_when(
      spk_lang_1 == "Spanish" | spk_lang_2 == "Spanish" ~ 5,
      spk_lang_1 == "Portuguese" | spk_lang_2 == "Portuguese" ~ 4,
      spk_lang_1 == "French" | spk_lang_2 == "French" ~ 3,
      spk_lang_1 %in% c("Urdu", "Hindi", "Bengali", "Russian") |
        spk_lang_2 %in% c("Urdu", "Hindi", "Bengali", "Russian") ~ 2,
      spk_lang_1 %in% c("Mandarin", "Standard Arabic", "None of these") |
        spk_lang_2 %in% c("Mandarin", "Standard Arabic", "None of these") ~ 1,
      spk_lang_1 == "English" ~ 0,
      TRUE ~ NA_integer_),
    acc_sub_region = case_when(
      spk_region == "Americas" & spk_sub_region == "Central" ~ 5,
      spk_region == "Americas" & spk_sub_region == "Northern" ~ 4,
      spk_region == "Americas" & spk_sub_region == "Caribbean" ~ 3,
      spk_region == "Americas" & spk_sub_region == "Southern" ~ 2,
      spk_region == "Europe" ~ 1,
      TRUE ~ 0
    ),
    spk_accent_type = gsub("\\[|\\]|\"", "\\1", spk_accent_type),
    spk_accent_type = case_when(
      is.na(spk_accent_type) ~ list("y"),
      TRUE ~ str_split(spk_accent_type, ",")),
    spk_fluency = case_when(
      spk_lang_1 == "English" ~ spk_fluency_1,
      spk_lang_2 == "English" ~ spk_fluency_2,
      TRUE ~ NA_integer_
    )) %>%
  select(participant, spk_accent_strength, spk_accent_type,
         spk_ease, spk_percep, spk_fluency, 
         acc_lang, acc_sub_region)
```

```{r explore_2}
# Load participant data
dat_pro <- read.csv("~/Mirror/dissertation/12_behavioral/data/quality/dat_pro.csv") %>%
  select(participant, par_accent_type, par_accent_strength) %>%
  mutate(par_accent_type = gsub("\\[|\\]|\"", "\\1", par_accent_type)) %>%
  replace_na(list(par_accent_strength = 0)) %>%
  rowwise() %>%
  mutate(par_accent_type = case_when(
    is.na(par_accent_type) ~ list("x"),
    TRUE ~ str_split(par_accent_type, ",")))
```

```{r explore_3}
dat_corr <- dat_survey %>% 
  left_join(dat_pro, by = "participant") %>%
  rowwise() %>%
  mutate(comp_accent_type = list(par_accent_type[par_accent_type %in% spk_accent_type]),
    comp_accent_num = length(comp_accent_type),
    spk_accent_len = case_when(
      spk_accent_type[[1]] == "y" ~ 0,
      TRUE ~ length(spk_accent_type)
    ),
    par_accent_len = case_when(
      par_accent_type[[1]] == "x" ~ 0,
      TRUE ~ length(par_accent_type)
    ),
    comp_accent_denom = spk_accent_len + par_accent_len - comp_accent_num,
    comp_accent_pct = comp_accent_num/comp_accent_denom) %>%
  select(-c(spk_accent_type, par_accent_type, comp_accent_type,
            comp_accent_num, spk_accent_len, par_accent_len, comp_accent_denom)) %>%
  left_join(dat_test_explore %>% 
              ungroup() %>%
              select(participant, d_prime_test, rt_diff_z), 
            by = "participant") %>%
  select(-participant)
```

```{r explore_4}
# Order column names
dat_corr_cols <- c("spk_ease", "spk_percep", "spk_accent_strength", 
                   "spk_fluency", "acc_lang", "acc_sub_region",
                   "comp_accent_pct", "par_accent_strength", 
                   "d_prime_test", "rt_diff_z")

# Make new column names
dat_corr_new <- c("Talker ease", "Talker comprehensibility", "Talker accent strength",
                  "Talker English rating", "Talker language accuracy", "Talker region accuracy",
                  "Own accent comparison", "Own accent strength", 
                  "Test accuracy", "Test RT")

# Reorder
dat_corr <- dat_corr %>%
  select(all_of(dat_corr_cols))

# Rename
colnames(dat_corr) <- dat_corr_new
```

```{r explore_5}
# Compute and save
corr_list <- psych::corr.test(as.matrix(dat_corr),
                              adj = "hommel")
corr_form <- apa_corr(corr_list)

# Get r and p values
corr_r <- corr_list$r
corr_p <- corr_list$p

# Make initial plot
corr_plot <- ggcorrplot::ggcorrplot(corr_r, hc.order = FALSE, type = "upper", 
                                    outline.col = "#FFFFFF", lab = FALSE,
                                    ggtheme = ggplot2::theme_minimal(), 
                                    colors = col_corr, p.mat = corr_p,
                                    insig = "pch", pch.cex = 1, pch = 20, 
                                    pch.col = "#FFFFFF", show.legend = TRUE)

# Get asterisks
corr_labs <- corr_p  %>%  
  as.data.frame() %>%
  mutate_all(labs_func) %>%
  rownames_to_column(var = "Var1") %>%
  pivot_longer(cols = c(everything(), -Var1), 
               names_to = "Var2", values_to = "lab") %>%
  right_join(corr_plot$data, by = c("Var1", "Var2"))

# Make plot
corr_plot_fin <- corr_plot +
  geom_text(aes(x = corr_labs$Var1,
                y = corr_labs$Var2),
            label = corr_labs$lab,
            size = 3*1.5,
            color = "#000000") +
  theme(axis.text.y = element_text(hjust = 1),
        text = element_text(family = font_fam, size = 20),
        legend.title = element_blank(),
        legend.ticks = element_blank(),
        legend.position = "right",
        legend.key.height = unit(3, "lines"),
        legend.text = element_text(hjust = 1, size = 10))
```

```{r explore_5_save_plot, include = FALSE}
# Save plot and crop to remove white space
ggsave("outputs/corr_plot_1.png", corr_plot_fin, width = 2100, height = 2100, unit = "px", dpi = 300)
knitr::plot_crop("outputs/corr_plot_1.png")
```

```{r explore_6}
# Load in correlation table from plot file
corr_tab <- corr_form %>%
  dplyr::filter(p < .05)

# Pull values
corr_ease_d <- corr_tab %>% dplyr::filter(Var1 == "Talker ease" & Var2 == "Test accuracy") %>% pull(report)
corr_comp_d <- corr_tab %>% dplyr::filter(Var1 == "Talker comprehensibility" & Var2 == "Test accuracy") %>% pull(report)
corr_ease_comp <- corr_tab %>% dplyr::filter(Var2 == "Talker comprehensibility" & Var1 == "Talker ease") %>% pull(report)
```

```{r explore_7}
# Make composite scores
dat_survey_sum <- dat_survey %>%
  rowwise() %>%
  mutate(spk_accent_rev = case_when(
    spk_accent_strength == 5 ~ 1,
    spk_accent_strength == 4 ~ 2,
    spk_accent_strength == 3 ~ 3,
    spk_accent_strength == 2 ~ 4,
    spk_accent_strength == 1 ~ 5,
    TRUE ~ NA_integer_
  ),
  spk_mean = mean(c(spk_accent_rev, spk_ease, spk_percep, spk_fluency), na.rm = TRUE),
  acc_sum = sum(c(acc_lang, acc_sub_region), na.rm = TRUE)) %>% 
  ungroup()
```

```{r explore_8}
# Join
dat_prime_survey <- dat_test_explore %>% 
  left_join(dat_survey_sum, by = "participant") %>%
  mutate(speaker = speaker - 2,
         train_wout = if_else(train_type == "none", "Without", "With"),
         test_task = factor(test_task, 
                            levels = c("match", "prime"),
                            labels = c("Matching", "Primed lexical decision")),
         across(
           .cols = c(cond_exp, speaker,
                     train_type, train_wout),
           .fns = as.factor
         ),
         spk_mean_cent = spk_mean - mean(spk_mean),
         acc_sum_cent = acc_sum - mean(acc_sum))

# Assign contrast codes
contrasts(dat_prime_survey$speaker) <- contrast_talk
contrasts(dat_prime_survey$train_wout) <- contrast_wout
contrasts(dat_prime_survey$test_task) <- contrast_task
```

```{r explore_9_mod, message = FALSE, warning = FALSE}
# Talker rating
mod_spk <- lm(spk_mean ~ speaker*train_wout + test_task, dat_prime_survey)

# Comparison
mod_spk_comp <- Anova(mod_spk, test = "Chi", type = "III")

# Format
mod_spk_comp_speaker_form <- mod_comp_lm(mod_spk_comp, "speaker")
mod_spk_comp_train_form <- mod_comp_lm(mod_spk_comp, "train_wout")
```

```{r explore_9_vals, message = FALSE, warning = FALSE}
# Get means
mod_spk_means_speaker <- emmeans(mod_spk, ~ speaker)
mod_spk_means_train <- emmeans(mod_spk, ~ train_wout)

# Format
mod_spk_means_speaker_form <- mod_spk_means_speaker %>%
  summary(type = "response") %>%
  rowwise() %>%
  mutate(report = sprintf("*M* = %.2f, 95%% CI [%.2f, %.2f]",
                          emmean,
                          `lower.CL`, `upper.CL`))
mod_spk_means_train_form <- mod_spk_means_train %>%
  summary(type = "response") %>%
  rowwise() %>%
  mutate(report = sprintf("*M* = %.2f, 95%% CI [%.2f, %.2f]",
                          emmean,
                          `lower.CL`, `upper.CL`))

# Pull
mod_train_with <- mod_spk_means_train_form %>%
  dplyr::filter(train_wout == "With") %>%
  pull(report)
mod_train_without <- mod_spk_means_train_form %>%
  dplyr::filter(train_wout == "Without") %>%
  pull(report)

# Comparison
mod_spk_cont_speaker <- mod_spk_means_speaker %>% 
  pairs(adjust = "hommel") %>%
  pair_comp("speaker1 - speaker4")

mod_spk_cont_train <- mod_spk_means_train %>% 
  pairs() %>%
  pair_comp("With - Without")
```

```{r explore_10_mod, message = FALSE, warning = FALSE}
# Talker accuracy
mod_lang <- lm(acc_sum ~ speaker*train_wout + test_task, dat_prime_survey)

# Comparison
mod_lang_comp <- Anova(mod_lang, test = "Chi", type = "III")
```

```{r explore_11_mod, message = FALSE, warning = FALSE}
# Number of data points included
num_prime <- nrow(dat_prime_survey %>% 
                    dplyr::filter(between(d_prime_test, -4, 4)))

# Talker rating
mod_prime <- lm(d_prime_test ~ speaker*train_wout + test_task + spk_mean_cent, 
                dat_prime_survey %>% 
                    dplyr::filter(between(d_prime_test, -4, 4)))

# Comparison
mod_prime_comp <- Anova(mod_prime, test = "Chi", type = "III")

# Format
mod_prime_comp_spk_mean <- mod_comp_lm(mod_prime_comp, "spk_mean_cent")
mod_prime_comp_speaker <- mod_comp_lm(mod_prime_comp, "speaker")
```

```{r explore_11_vals, message = FALSE, warning = FALSE}
# Get means
mod_prime_means <- emmeans(mod_prime, ~ speaker)

# Format
mod_prime_means_form <- mod_prime_means %>%
  summary(type = "response")

# Comparison
mod_prime_cont <- mod_prime_means %>% 
  pairs(adjust = "hommel") %>%
  data.frame() %>%
  dplyr::filter(`p.value` <= .05)

# Beta
mod_prime_beta_mean <- sprintf("$\\beta$ = %.3f", mod_prime$coefficients[which(names(mod_prime$coefficients) == "spk_mean_cent")])


  # mutate(contrast = str_remove_all(contrast, "speaker")) %>%
  # separate(contrast, sep = " - ", into = c("x", "xend"), 
  #          remove = FALSE) %>%
  # mutate(x = as.numeric(x),
  #        xend = as.numeric(xend),
  #        y_line_1 = xend - x + 1.5,
  #        y_line_2 = case_when(
  #          x == 1 ~ 0,
  #          x == 2 ~ 0.35,
  #          x == 3 ~ 0.7
  #        ),
  #        y_line = y_line_1 + y_line_2,
  #        x = x - 0.1,
  #        xend = xend + 0.1,
  #        y_lab = y_line + 0.07) %>%
  # rowwise() %>% 
  # mutate(lab_pos = mean(c(x, xend)),
  #        labs = labs_func(`p.value`))
```

```{r explore_11_setup}
# Set labels
train_labs <- c("With training\n(Exposure groups)", "Without training\n(Test-only group)")
names(train_labs) <- c("With", "Without")
null_labs <- c("", "")
names(null_labs) <- c("With", "Without")

prime_match_mean <- dat_prime_survey %>% 
  dplyr::filter(test_task == "Matching") %>%
  pull(d_prime_test) %>%
  mean()

prime_match_sd <- dat_prime_survey %>% 
  dplyr::filter(test_task == "Matching") %>%
  pull(d_prime_test) %>%
  sd()

prime_match_breaks <- sapply(c(prime_match_mean - prime_match_sd * 4, 
                     prime_match_mean - prime_match_sd * 2,
                     prime_match_mean, 
                     prime_match_mean + prime_match_sd * 2,
                     prime_match_mean + prime_match_sd * 4), 
                     function(x) round(x, 1))

prime_ldt_mean <- dat_prime_survey %>% 
  dplyr::filter(test_task == "Primed lexical decision") %>%
  pull(d_prime_test) %>%
  mean()

prime_ldt_sd <- dat_prime_survey %>% 
  dplyr::filter(test_task == "Primed lexical decision") %>%
  pull(d_prime_test) %>%
  sd()

prime_ldt_breaks <- sapply(c(prime_ldt_mean - prime_ldt_sd * 4, 
                     prime_ldt_mean - prime_ldt_sd * 2,
                     prime_ldt_mean, 
                     prime_ldt_mean + prime_ldt_sd * 2,
                     prime_ldt_mean + prime_ldt_sd * 4),
                     function(x) round(x, 1))
```

```{r explore_11_plot, include = FALSE}
plot_prime_match <- ggplot() +
  geom_half_boxplot(data = dat_prime_survey %>% 
                      dplyr::filter(between(d_prime_test, -4, 4) &
                                      test_task == "Matching"), 
               aes(x = speaker, y = d_prime_test,
                   color = speaker, 
                   fill = speaker),
               size = g_line*1.25, alpha = alpha_lev,
               outlier.shape = NA, errorbar.draw = FALSE)  +
  geom_half_point(data = dat_prime_survey %>% 
                      dplyr::filter(between(d_prime_test, -4, 4) &
                                      test_task == "Matching"), 
               aes(x = speaker, y = d_prime_test,
                   color = speaker, 
                   fill = speaker),
               alpha = alpha_lev) +
  facet_grid(test_task ~ train_wout,
             switch = "y",
             labeller = labeller(train_wout = train_labs)) +
  geom_point(data = mod_prime_means_form %>%
               dplyr::filter(test_task == "Matching"),
             aes(x = speaker, y = emmean), 
             position = position_dodge(width = g_dodge),
             color = "black", size = g_point*1.5) +
  geom_errorbar(data = mod_prime_means_form %>%
               dplyr::filter(test_task == "Matching"),
             aes(x = speaker, 
                 ymin = `lower.CL`, ymax = `upper.CL`), 
             position = position_dodge(width = g_dodge),
             color = "black", width = 0.25, size = g_line) +
  geom_segment(data = mod_prime_cont %>%
               dplyr::filter(test_task == "Matching"),
               aes(x = x, xend = xend, y = y_line)) +
  geom_text(data = mod_prime_cont %>%
               dplyr::filter(test_task == "Matching"),
            aes(x = lab_pos, y = y_lab, label = labs),
            fontface = "bold", size = sig_size) +
  scale_color_manual(values = col_talk) +
  scale_fill_manual(values = col_talk) +
  scale_y_continuous(name = "Test accuracy (d-prime)",
                     breaks = seq(-6, 6, 2),
                     sec.axis = sec_axis(transform = ~ . * prime_match_sd + prime_match_mean,
                                         name = "Test accuracy (rate difference)",
                                         breaks = prime_match_breaks)) +
  xlab("Talker") +
  coord_cartesian(ylim = c(-4.5, 4.5)) +
  theme_minimal() +
  theme(text = element_text(family = font_fam, size = text_size),
        strip.placement = "outside",
        strip.switch.pad.grid = unit(2, "cm"),
        axis.title.y = element_text(vjust = -10)) +
  guides(color = "none", fill = "none")

plot_prime_ldt <- ggplot() +
  geom_half_boxplot(data = dat_prime_survey %>% 
                      dplyr::filter(between(d_prime_test, -4, 4) &
                                      test_task == "Primed lexical decision"), 
               aes(x = speaker, y = d_prime_test,
                   color = speaker, 
                   fill = speaker),
               size = g_line*1.25, alpha = alpha_lev,
               outlier.shape = NA, errorbar.draw = FALSE)  +
  geom_half_point(data = dat_prime_survey %>% 
                      dplyr::filter(between(d_prime_test, -4, 4) &
                                      test_task == "Primed lexical decision"), 
               aes(x = speaker, y = d_prime_test,
                   color = speaker, 
                   fill = speaker),
               alpha = alpha_lev) +
  facet_grid(test_task ~ train_wout,
             switch = "y",
             labeller = labeller(train_wout = null_labs)) +
  geom_point(data = mod_prime_means_form %>%
               dplyr::filter(test_task == "Primed lexical decision"),
             aes(x = speaker, y = emmean), 
             position = position_dodge(width = g_dodge),
             color = "black", size = g_point*1.5) +
  geom_errorbar(data = mod_prime_means_form %>%
               dplyr::filter(test_task == "Primed lexical decision"),
             aes(x = speaker, 
                 ymin = `lower.CL`, ymax = `upper.CL`), 
             position = position_dodge(width = g_dodge),
             color = "black", width = 0.25, size = g_line) +
  geom_segment(data = mod_prime_cont %>%
               dplyr::filter(test_task == "Primed lexical decision"),
               aes(x = x, xend = xend, y = y_line)) +
  geom_text(data = mod_prime_cont %>%
               dplyr::filter(test_task == "Primed lexical decision"),
            aes(x = lab_pos, y = y_lab, label = labs),
            fontface = "bold", size = sig_size) +
  scale_color_manual(values = col_talk) +
  scale_fill_manual(values = col_talk) +
  scale_y_continuous(name = "Test accuracy (d-prime)",
                     breaks = seq(-6, 6, 2),
                     sec.axis = sec_axis(transform = ~ . * prime_ldt_sd + prime_ldt_mean,
                                         name = "Test accuracy (rate difference)",
                                         breaks = prime_ldt_breaks)) +
  xlab("Talker") +
  coord_cartesian(ylim = c(-4.5, 4.5)) +
  theme_minimal() +
  theme(text = element_text(family = font_fam, size = text_size),
        strip.placement = "outside",
        strip.switch.pad.grid = unit(2, "cm"),
        axis.title.y = element_text(vjust = -10)) +
  guides(color = "none", fill = "none")
```

```{r explore_11_plot_save, include = FALSE}
plot_prime <- plot_prime_match + plot_prime_ldt +
  plot_layout(nrow = 2, axes = "collect")

# Save plot and crop to remove white space
ggsave("outputs/plot_explore_prime.png", plot_prime,
       width = 4200, height = 3600, unit = "px", dpi = 300)
knitr::plot_crop("outputs/plot_explore_prime.png")
```

```{r explore_12_mod, message = FALSE, warning = FALSE}
# Number of data points included
num_rt <- nrow(dat_prime_survey %>% 
                 dplyr::filter(between(rt_diff_z, -4, 4)))

# Test task RT diff
mod_rt <- lm(rt_diff_z ~ speaker*train_wout + test_task + spk_mean_cent, 
             dat_prime_survey %>% dplyr::filter(between(rt_diff_z, -4, 4)))

# Comparison
mod_rt_comp <- Anova(mod_rt, test = "Chi", type = "III")

# Format
mod_rt_comp_int <- mod_comp_lm(mod_rt_comp, "speaker:train_wout")
mod_rt_comp_spk_mean <- mod_comp_lm(mod_rt_comp, "spk_mean_cent")
mod_rt_comp_speaker <- mod_comp_lm(mod_rt_comp, "speaker")
```

```{r explore_12_vals, message = FALSE, warning = FALSE}
# Get means
mod_rt_means <- emmeans(mod_rt, ~ speaker)

# Format
mod_rt_means_form <- mod_rt_means %>%
  summary(type = "response") %>%
  rowwise() %>%
  mutate(report = sprintf("*M* = %.2f, 95%% CI [%.2f, %.2f]",
                          emmean,
                          `lower.CL`, `upper.CL`))

# Comparison
mod_rt_cont <- mod_rt_means %>% 
  pairs(adjust = "hommel") %>%
  data.frame() %>%
  dplyr::filter(`p.value` <= .05) 

# Beta
mod_rt_beta_mean <- sprintf("$\\beta$ = %.3f", mod_rt$coefficients[which(names(mod_rt$coefficients) == "spk_mean_cent")])

  # mutate(contrast = str_remove_all(contrast, "speaker")) %>%
  # separate(contrast, sep = " - ", into = c("x", "xend"), 
  #          remove = FALSE) %>%
  # mutate(x = as.numeric(x),
  #        xend = as.numeric(xend),
  #        y_line_1 = xend - x + 1,
  #        y_line_2 = case_when(
  #          x == 1 ~ 0,
  #          x == 2 ~ 0.35,
  #          x == 3 ~ 0.7
  #        ),
  #        y_line = y_line_1 + y_line_2,
  #        x = x - 0.1,
  #        xend = xend + 0.1,
  #        y_lab = y_line + 0.07) %>%
  # rowwise() %>% 
  # mutate(lab_pos = mean(c(x, xend)),
  #        labs = labs_func(`p.value`))
```

```{r explore_12_sub}
# Contrasts
mod_rt_means_cont_2 <- mod_rt_means %>% 
  pairs(adjust = "hommel", by = c("speaker", "test_task")) %>%
  data.frame() %>%
  dplyr::filter(`p.value` <= .05) %>%
  pair_comp("With - Without")


# Pull
mod_rt_means_with_1 <- mod_rt_means_form %>%
  dplyr::filter(speaker == 1 & 
                  train_wout == "With" & 
                  test_task == "Primed lexical decision") %>%
  pull(report)
mod_rt_means_wout_1 <- mod_rt_means_form %>%
  dplyr::filter(speaker == 1 & 
                  train_wout == "Without" & 
                  test_task == "Primed lexical decision") %>%
  pull(report)

# Raw means
mod_rt_means_raw <- dat_prime_survey %>% 
  dplyr::filter(speaker == 1 & test_task == "Primed lexical decision")

# T-tests
mod_rt_raw_comp <- t.test(mod_rt_means_raw %>% dplyr::filter(train_wout == "With") %>% pull(competitor),
       mod_rt_means_raw %>% dplyr::filter(train_wout == "Without") %>% pull(competitor))
mod_rt_raw_id <- t.test(mod_rt_means_raw %>% dplyr::filter(train_wout == "With") %>% pull(identity),
       mod_rt_means_raw %>% dplyr::filter(train_wout == "Without") %>% pull(identity))

# Pull
mod_rt_raw_comp_rep <- sprintf("*t*(%s) = %s, *p* %s", 
        df_formatting(mod_rt_raw_comp$parameter), 
        stat_formatting(mod_rt_raw_comp$statistic), 
        p_formatting(mod_rt_raw_comp$`p.value`))
mod_rt_raw_id_rep <- sprintf("*t*(%s) = %s, *p* %s", 
        df_formatting(mod_rt_raw_id$parameter), 
        stat_formatting(mod_rt_raw_id$statistic), 
        p_formatting(mod_rt_raw_id$`p.value`))
```

```{r explore_12_setup}
rt_match_mean <- dat_prime_survey %>% 
  dplyr::filter(test_task == "Matching") %>%
  pull(rt_diff_raw) %>%
  mean()

rt_match_sd <- dat_prime_survey %>% 
  dplyr::filter(test_task == "Matching") %>%
  pull(rt_diff_raw) %>%
  sd()

rt_match_breaks <- sapply(c(rt_match_mean - rt_match_sd * 4, 
                     rt_match_mean - rt_match_sd * 2,
                     rt_match_mean, 
                     rt_match_mean + rt_match_sd * 2,
                     rt_match_mean + rt_match_sd * 4), round)

rt_ldt_mean <- dat_prime_survey %>% 
  dplyr::filter(test_task == "Primed lexical decision") %>%
  pull(rt_diff_raw) %>%
  mean()

rt_ldt_sd <- dat_prime_survey %>% 
  dplyr::filter(test_task == "Primed lexical decision") %>%
  pull(rt_diff_raw) %>%
  sd()

rt_ldt_breaks <- sapply(c(rt_ldt_mean - rt_ldt_sd * 4, 
                     rt_ldt_mean - rt_ldt_sd * 2,
                     rt_ldt_mean, 
                     rt_ldt_mean + rt_ldt_sd * 2,
                     rt_ldt_mean + rt_ldt_sd * 4), round)
```

```{r explore_12_plot, include = FALSE}
plot_rt_match <- ggplot() +
  geom_half_boxplot(data = dat_prime_survey %>% 
                      dplyr::filter(between(rt_diff_z, -4, 4) &
                                      test_task == "Matching"), 
               aes(x = speaker, y = rt_diff_z,
                   color = speaker, 
                   fill = speaker),
               size = g_line*1.25, alpha = alpha_lev,
               outlier.shape = NA, errorbar.draw = FALSE)  +
  geom_half_point(data = dat_prime_survey %>% 
                      dplyr::filter(between(rt_diff_z, -4, 4) &
                                      test_task == "Matching"), 
               aes(x = speaker, y = rt_diff_z,
                   color = speaker, 
                   fill = speaker),
               alpha = alpha_lev) +
  facet_grid(test_task ~ train_wout,
             switch = "y",
             labeller = labeller(train_wout = train_labs)) +
  geom_point(data = mod_rt_means_form %>%
               dplyr::filter(test_task == "Matching"),
             aes(x = speaker, y = emmean), 
             position = position_dodge(width = g_dodge),
             color = "black", size = g_point*1.5) +
  geom_errorbar(data = mod_rt_means_form %>%
               dplyr::filter(test_task == "Matching"),
             aes(x = speaker, 
                 ymin = `lower.CL`, ymax = `upper.CL`), 
             position = position_dodge(width = g_dodge),
             color = "black", width = 0.25, size = g_line) +
  geom_segment(data = mod_rt_cont %>%
               dplyr::filter(test_task == "Matching"),
               aes(x = x, xend = xend, y = y_line)) +
  geom_text(data = mod_rt_cont %>%
               dplyr::filter(test_task == "Matching"),
            aes(x = lab_pos, y = y_lab, label = labs),
            fontface = "bold", size = sig_size) +
  scale_color_manual(values = col_talk) +
  scale_fill_manual(values = col_talk) +
  scale_y_continuous(name = "Test RT (z-scored difference)",
                     breaks = seq(-6, 6, 2),
                     sec.axis = sec_axis(transform = ~ . * rt_match_sd + rt_match_mean,
                                         name = "Test RT (raw difference)",
                                         breaks = rt_match_breaks)) +
  xlab("Talker") +
  coord_cartesian(ylim = c(-4.5, 4.5)) +
  theme_minimal() +
  theme(text = element_text(family = font_fam, size = text_size),
        strip.placement = "outside",
        strip.switch.pad.grid = unit(2, "cm"),
        axis.title.y = element_text(vjust = -10)) +
  guides(color = "none", fill = "none")

plot_rt_ldt <- ggplot() +
  geom_half_boxplot(data = dat_prime_survey %>% 
                      dplyr::filter(between(rt_diff_z, -4, 4) &
                                      test_task == "Primed lexical decision"), 
               aes(x = speaker, y = rt_diff_z,
                   color = speaker, 
                   fill = speaker),
               size = g_line*1.25, alpha = alpha_lev,
               outlier.shape = NA, errorbar.draw = FALSE)  +
  geom_half_point(data = dat_prime_survey %>% 
                      dplyr::filter(between(rt_diff_z, -4, 4) &
                                      test_task == "Primed lexical decision"), 
               aes(x = speaker, y = rt_diff_z,
                   color = speaker, 
                   fill = speaker),
               alpha = alpha_lev) +
  facet_grid(test_task ~ train_wout,
             switch = "y",
             labeller = labeller(train_wout = null_labs)) +
  geom_point(data = mod_rt_means_form %>%
               dplyr::filter(test_task == "Primed lexical decision"),
             aes(x = speaker, y = emmean), 
             position = position_dodge(width = g_dodge),
             color = "black", size = g_point*1.5) +
  geom_errorbar(data = mod_rt_means_form %>%
               dplyr::filter(test_task == "Primed lexical decision"),
             aes(x = speaker, 
                 ymin = `lower.CL`, ymax = `upper.CL`), 
             position = position_dodge(width = g_dodge),
             color = "black", width = 0.25, size = g_line) +
  geom_segment(data = mod_rt_cont %>%
               dplyr::filter(test_task == "Primed lexical decision"),
               aes(x = x, xend = xend, y = y_line)) +
  geom_text(data = mod_rt_cont %>%
               dplyr::filter(test_task == "Primed lexical decision"),
            aes(x = lab_pos, y = y_lab, label = labs),
            fontface = "bold", size = sig_size) +
  scale_color_manual(values = col_talk) +
  scale_fill_manual(values = col_talk) +
  scale_y_continuous(name = "Test RT (z-scored difference)",
                     breaks = seq(-6, 6, 2),
                     sec.axis = sec_axis(transform = ~ . * rt_ldt_sd + rt_ldt_mean,
                                         name = "Test RT (raw difference)",
                                         breaks = rt_ldt_breaks)) +
  xlab("Talker") +
  coord_cartesian(ylim = c(-4.5, 4.5)) +
  theme_minimal() +
  theme(text = element_text(family = font_fam, size = text_size),
        strip.placement = "outside",
        strip.switch.pad.grid = unit(2, "cm"),
        axis.title.y = element_text(vjust = -10)) +
  guides(color = "none", fill = "none")
```

```{r explore_12_plot_save, include = FALSE}
plot_rt <- plot_rt_match + plot_rt_ldt +
  plot_layout(nrow = 2, axes = "collect")

# Save plot and crop to remove white space
ggsave("outputs/plot_explore_rt.png", plot_rt,
       width = 4200, height = 3600, unit = "px", dpi = 300)
knitr::plot_crop("outputs/plot_explore_rt.png")
```

