---
pagetitle: "general"
---

```{r setup_3}
# Source
source("0_load_eeg.R")

# Resave text size
text_size <- 20
```

```{r eeg_par_sum}
# Number of original participants
eeg_par_all <- nrow(eeg_lhq)

# Number of eligible participants
eeg_par_elig <- nrow(eeg_lhq %>% dplyr::filter(health_flag == 0))

# Calculate age stats
eeg_par_age <- eeg_lhq %>%
  summarise(mean = round(mean(demo_age), 0),
            sd = round(sd(demo_age), 0),
            min = min(demo_age), 
            max = max(demo_age)) %>%
  ungroup() %>%
  mutate(age = sprintf("*M* = %.0f, *SD* = %.0f, Min = %.0f, Max = %.0f", mean, sd, min, max)) %>%
  pull(age)

# Count per category
eeg_par_sex <- eeg_lhq %>%
  group_by(demo_gender) %>%
  summarise(count = n(), .groups = "keep") %>%
  mutate(report = paste(demo_gender, count, sep = " = "),
         temp = 1) %>%
  group_by(temp) %>%
  summarise(gender = toString(report)) %>%
  pull(gender)
```

```{r eeg_par_lhq}
# Count per category
eeg_par_info <- eeg_lhq %>%
  arrange(lang_eng_dialect) %>%
  group_by(lang_eng_dialect, demo_race) %>%
  summarise(count = n(), .groups = "keep") %>%
  pivot_wider(id_cols = demo_race, names_from = lang_eng_dialect, 
              values_from = count, values_fill = 0) %>%
  arrange(demo_race) %>%
  rename(`Race and ethnicity` = demo_race)
```

```{r eeg_vot_load}
# Load EEG VOT info
stim_full <- all_trial_dat %>% 
  select(target, target_cond, stim_onset, vot) %>% 
  distinct()

# Make table
on_vot <- stim_full %>%
  distinct() %>%
  dplyr::filter(stim_onset %in% c("p", "t", "k")) %>%
  group_by(target_cond, stim_onset) %>%
  summarise(n = n(),
            mean = round(mean(vot),0),
            sd = round(sd(vot),0),
            min = round(min(vot),0),
            max = round(max(vot),0), .groups = "keep") %>%
  mutate(range = paste(min, max, sep = "-")) %>%
  select(-c(min, max)) %>% 
  ungroup() %>%
  mutate(stim_onset = sprintf("/%s/", stim_onset),
         stim_onset = factor(stim_onset, levels = c("/p/", "/t/", "/k/")),
         target_cond = factor(target_cond, levels = c("exposure", "test"),
                              labels = c("Exposure", "Test"))) %>%
  arrange(target_cond, stim_onset)
```

```{r erp_rej_sum}
# Trials with ERP data
erp_trial_dat <- read.csv(paste(eeg_path, "output/all_trial_info.csv", sep = "/")) %>% 
  left_join(code_tab, by = c("T1Label", "T2Label", "T3Label")) %>%
  dplyr::filter(target_cond == "test")

# Total number of trials with ERP data
erp_trials_all <- erp_trial_dat %>% nrow()

# Number of trials with ERP data by participant
erp_trial_info <- erp_trial_dat %>% 
  group_by(id) %>%
  summarise(with_eeg = n())

# Number of trials available
erp_trials_possible <- nrow(erp_trial_info)*216

# Difference
erp_trials_diff <- erp_trials_possible - erp_trials_all
erp_trials_diff_pct <- pct_formatting(erp_trials_diff/erp_trials_possible)

# Average number of trials per participant
erp_trials_par <- zero_formatting(mean(erp_trial_info$with_eeg))

# Total number of accurate trials with ERP data
erp_trials_acc <- erp_n1_all %>% nrow()

# Number of accurate trials with ERP data by participant
erp_trial_acc_info <- erp_n1_all %>%
  group_by(id) %>%
  summarise(acc_with_eeg = n())

# Difference
erp_trials_acc_diff <- erp_trials_all - erp_trials_acc
erp_trials_acc_diff_pct <- pct_formatting(erp_trials_acc_diff/erp_trials_all)

# Average number of trials per participant
erp_trials_acc_par <- zero_formatting(mean(erp_trial_acc_info$acc_with_eeg))

# Number of accurate trials with ERP data by condition
erp_trial_acc_cond_info <- erp_n1_all %>%
  group_by(id, prime_cond) %>%
  summarise(cond_no = n(), .groups = "keep") %>%
  group_by(prime_cond) %>%
  summarise(cond_avg = mean(cond_no))

# Pull values
avg_id <- zero_formatting(erp_trial_acc_cond_info$cond_avg[which(erp_trial_acc_cond_info$prime_cond == "identity")])
avg_comp <- zero_formatting(erp_trial_acc_cond_info$cond_avg[which(erp_trial_acc_cond_info$prime_cond == "competitor")])
avg_un <- zero_formatting(erp_trial_acc_cond_info$cond_avg[which(erp_trial_acc_cond_info$prime_cond == "unrelated")])
```

```{r behave_rej_sum}
# Comparison trials
behave_trials_all_no <- nrow(behave_trials_all)
behave_trials_no <- nrow(behave_trials_clean)
behave_trials_diff <- behave_trials_all_no - behave_trials_no
behave_trials_diff_pct <- pct_formatting(behave_trials_diff/behave_trials_all_no)
```

```{r omni_behave_1}
# Run model
omni_behave <- glmer(acc ~ target_cond*exp_cent + vot_cent + freq_cent +
             (1|prime:target) + (target_cond|id),
           data = behave_trials_clean,
           nAGQ = 0,
           family = "binomial")

# Model comparison
omni_behave_comp <- Anova(omni_behave, test = "Chi", type = "II")
```

```{r omni_behave_2}
# Get mean trends
omni_behave_means <- emtrends(omni_behave, "target_cond", "exp_cent")

# Format
omni_behave_means_tab <- omni_behave_means %>% 
  data.frame() %>%
  rowwise() %>%
  mutate(report = sprintf("*M* = %.3f, 95%% CI [%.3f, %.3f]", 
                          `exp_cent.trend`, `asymp.LCL`, `asymp.UCL`))
```

```{r omni_behave_3}
# Get means at beginning and end
omni_behave_est <- emmeans(omni_behave, ~ target_cond*exp_cent, 
                           at = list(exp_cent = c(-36,36)))

# Format
omni_behave_est_form <- omni_behave_est %>%
  summary(type = "response") %>%
  mutate(ci = sprintf("95%% CI [%.2f, %.2f]", `asymp.LCL`, `asymp.UCL`),
         mean = num_formatting(prob),
         report = sprintf("%s (%s)", mean, ci))
```

```{r omni_behave_4}
# Get differences at beginning and end
omni_behave_est_cont_exp <- pairs(omni_behave_est, by = "exp_cent", adj = "hommel") %>%
  data.frame() %>%
  rename(cond = exp_cent) %>%
  mutate(cond = as.character(cond))

# Get differences between types
omni_behave_est_cont_target <- pairs(omni_behave_est, by = "target_cond", adj = "hommel") %>%
  data.frame() %>%
  rename(cond = target_cond)

# Combine and format
omni_behave_est_cont <- bind_rows(omni_behave_est_cont_exp, omni_behave_est_cont_target) %>%
  rowwise() %>%
  mutate(z = stat_formatting(`z.ratio`),
         p = p_formatting(`p.value`),
         report = sprintf("*z* = %s, *p* %s", z, p))
```

```{r behave_acc_1}
# Pull model comparison stats
behave_comp_target <- mod_comp(omni_behave_comp, "target_cond")
behave_comp_exp <- mod_comp(omni_behave_comp, "exp_cent")
behave_comp_int <- mod_comp(omni_behave_comp, "target_cond:exp_cent")

# Means
omni_behave_means_filler <- omni_behave_means_tab$report[which(omni_behave_means_tab$target_cond == "filler")]
omni_behave_means_test <- omni_behave_means_tab$report[which(omni_behave_means_tab$target_cond == "test")]

# Contrasts
omni_behave_cont_report <- pairs(omni_behave_means, adj = "hommel") %>%
  pair_comp("filler - test")
```

```{r behave_acc_2}
# Means
omni_behave_est_filler_1 <- omni_behave_est_form %>% 
  dplyr::filter(target_cond == "filler" & exp_cent == -36) %>% pull(report)
omni_behave_est_filler_2 <- omni_behave_est_form %>% 
  dplyr::filter(target_cond == "filler" & exp_cent == 36) %>% pull(report)
omni_behave_est_test_1 <- omni_behave_est_form %>% 
  dplyr::filter(target_cond == "test" & exp_cent == -36) %>% pull(report)
omni_behave_est_test_2 <- omni_behave_est_form %>% 
  dplyr::filter(target_cond == "test" & exp_cent == 36) %>% pull(report)

# Contrasts
omni_behave_est_cont_filler <- omni_behave_est_cont %>% dplyr::filter(cond == "filler") %>% pull(report)
omni_behave_est_cont_test <- omni_behave_est_cont %>% dplyr::filter(cond == "test") %>% pull(report)
omni_behave_est_cont_1 <- omni_behave_est_cont %>% dplyr::filter(cond == "-36") %>% pull(report)
omni_behave_est_cont_2 <- omni_behave_est_cont %>% dplyr::filter(cond == "36") %>% pull(report)
```

```{r behave_acc_plot, include = FALSE}
# Get means
behave_plot_dat <- emmip(omni_behave, target_cond ~ exp_cent, CIs = TRUE, 
      at = list(exp_cent = seq(-36,36,1)), plotit = FALSE, type = "response") %>%
  mutate(target_cond = factor(target_cond, levels = c("test", "filler"),
                              labels = c("Test", "Filler")))

# Plot
behave_plot_plot <- ggplot(behave_plot_dat, aes(x = exp_cent, y = yvar, color = target_cond)) +
  geom_line(size = 1.75) +
  geom_ribbon(aes(ymin = LCL, ymax = UCL, fill = target_cond), alpha = 0.4, color = NA) +
  scale_color_manual(values = c("#41b6c4", "#bbbbbb"), name = "Target type") +
  scale_fill_manual(values = c("#41b6c4", "#bbbbbb"), name = "Target type") +
  scale_x_continuous(breaks = seq(-36, 36, 12)) +
  scale_y_continuous(breaks = seq(0.85, 1.00, 0.05)) +
  coord_cartesian(xlim = c(-36, 36), ylim = c(0.85, 1.00)) +
  xlab("Amount of exposure (mean-centered)") +
  ylab("Estimated marginal mean accuracy") +
  theme_minimal() +
  theme(legend.position = "bottom",
        text = element_text(family = font_fam, size = text_size),
        axis.ticks = element_blank(),
        plot.title = element_text(size = text_size, hjust = 0.5))

# Save plot and crop to remove white space
ggsave("outputs/behave_plot.png", behave_plot_plot,
       width = 3600, height = 2100, unit = "px", dpi = 300)
knitr::plot_crop("outputs/behave_plot.png", quiet = TRUE)
```

```{r omni_test_1}
# Run omnibus
omni_test <- glmer(acc ~ prime_cond*exp_cent + vot_cent + freq_cent +
                     (1|target) + (prime_cond|id),
                   data = test_trial_dat_clean,
                   nAGQ = 0,
                   family = "binomial")

# Model comparison
omni_test_comp <- Anova(omni_test, test = "Chi", type = "II")
```

```{r omni_test_2}
# Get mean accuracy by prime
omni_test_prime <- emmeans(omni_test, "prime_cond")

# Format
omni_test_prime_tab <- omni_test_prime %>% 
  summary(type = "response") %>%
  rowwise() %>%
  mutate(report = sprintf("*M* = %.2f, 95%% CI [%.2f, %.2f]", 
                          prob, `asymp.LCL`, `asymp.UCL`))
```

```{r omni_test_3}
# Get contrasts
omni_test_prime_cont <- omni_test_prime %>% 
  pairs(adj = "hommel")

# Get slope
omni_test_exp_slope <- getME(omni_test, "beta")[4]

# Format 
omni_test_exp_slope_report <- sprintf("$\\beta$ = %.3f", omni_test_exp_slope)
```

```{r test_acc}
# Pull model comparison stats
test_comp_prime <- mod_comp(omni_test_comp, "prime_cond")
test_comp_exp <- mod_comp(omni_test_comp, "exp_cent")
test_comp_int <- mod_comp(omni_test_comp, "prime_cond:exp_cent")

# Means
omni_test_prime_id <- omni_test_prime_tab$report[which(omni_test_prime_tab$prime_cond == "identity")]
omni_test_prime_compete <- omni_test_prime_tab$report[which(omni_test_prime_tab$prime_cond == "competitor")]
omni_test_prime_un <- omni_test_prime_tab$report[which(omni_test_prime_tab$prime_cond == "unrelated")]

# contrasts
omni_test_cont_id_compete <- pair_comp(omni_test_prime_cont, "identity - competitor")
omni_test_cont_id_un <- pair_comp(omni_test_prime_cont, "identity - unrelated")
omni_test_cont_compete_un <- pair_comp(omni_test_prime_cont, "competitor - unrelated")
```

```{r test_acc_plot, include = FALSE}
# Get means
test_plot_dat <- emmip(omni_test, prime_cond ~ exp_cent, CIs = TRUE, 
                       at = list(exp_cent = seq(-36,36,1)), type = "response", plotit = FALSE) %>%
  mutate(prime_cond = factor(prime_cond, levels = c("identity", "competitor", "unrelated"),
                             labels = c("Identity", "Competitor", "Unrelated")))

# Plot
test_plot_plot <- ggplot(test_plot_dat, aes(x = exp_cent, y = yvar, color = prime_cond)) +
  geom_line(size = 1.75) +
  geom_ribbon(aes(ymin = LCL, ymax = UCL, fill = prime_cond), alpha = 0.4, color = NA) +
  scale_color_manual(values = col_test, name = "Prime type") +
  scale_fill_manual(values = col_test, name = "Prime type") +
  scale_x_continuous(breaks = seq(-36, 36, 12)) +
  scale_y_continuous(breaks = seq(0.8, 1.0, 0.05)) +
  coord_cartesian(xlim = c(-36, 36), ylim = c(0.8, 1.0)) +
  xlab("Amount of exposure (mean-centered)") +
  ylab("Estimated marginal mean accuracy") +
  theme_minimal() +
  theme(legend.position = "bottom",
        text = element_text(family = font_fam, size = text_size),
        axis.ticks = element_blank(),
        plot.title = element_text(size = text_size, hjust = 0.5))

# Save plot and crop to remove white space
ggsave("outputs/test_plot.png", test_plot_plot,
       width = 3600, height = 2100, unit = "px", dpi = 300)
knitr::plot_crop("outputs/test_plot.png")
```

```{r omni_n1}
# Run model
omni_n1 <- lmer(volt ~ prime_cond*exp_cent + vot_cent + freq_cent +
                  (1|target) + (1|id) + (1|chan),
                data = erp_n1)

# Model comparison
omni_n1_comp <- Anova(omni_n1, test = "Chi", type = "II")

# Means
omni_n1_means <- emtrends(omni_n1, "prime_cond", "exp_cent")

# Pairwise comparisons
omni_n1_cont <- omni_n1_means %>% pairs(adj = "hommel")
```

```{r erp_n1_1}
# Pull model comparison stats
n1_comp_int <- mod_comp(omni_n1_comp, "prime_cond:exp_cent")
n1_comp_prime <- mod_comp(omni_n1_comp, "prime_cond")
n1_comp_exp <- mod_comp(omni_n1_comp, "exp_cent")

# Format means for exposure
omni_n1_means_tab <- omni_n1_means %>% 
  data.frame() %>%
  rowwise() %>%
  mutate(report = sprintf("*M* = %.3f, 95%% CI [%.3f, %.3f]", 
                          `exp_cent.trend`, `asymp.LCL`, `asymp.UCL`))

# Pull means
omni_n1_id <- omni_n1_means_tab %>% dplyr::filter(prime_cond == "identity") %>% pull(report)
omni_n1_compete <- omni_n1_means_tab %>% dplyr::filter(prime_cond == "competitor") %>% pull(report)
omni_n1_un <- omni_n1_means_tab %>% dplyr::filter(prime_cond == "unrelated") %>% pull(report)

# Pull pairwise contrasts
omni_n1_id_compete <- pair_comp(omni_n1_cont, "identity - competitor")
omni_n1_id_un <- pair_comp(omni_n1_cont, "identity - unrelated")
omni_n1_compete_un <- pair_comp(omni_n1_cont, "competitor - unrelated")
```

```{r erp_n1_2}
# Get means for prime
omni_n1_means_prime <- emmeans(omni_n1, ~ prime_cond*exp_cent, at = list(exp_cent = c(-36,36)))

# Format
omni_n1_means_prime_tab <- summary(omni_n1_means_prime) %>%
  mutate(report = sprintf("*M* = %.2f, 95%% CI [%.2f, %.2f]", 
                          emmean, `asymp.LCL`, `asymp.UCL`))

# Pull means
omni_n1_id_prime_1 <- omni_n1_means_prime_tab %>% 
  dplyr::filter(prime_cond == "identity" & exp_cent == -36) %>% pull(report)
omni_n1_id_prime_2 <- omni_n1_means_prime_tab %>% 
  dplyr::filter(prime_cond == "identity" & exp_cent == 36) %>% pull(report)
omni_n1_compete_prime_1 <- omni_n1_means_prime_tab %>% 
  dplyr::filter(prime_cond == "competitor" & exp_cent == -36) %>% pull(report)
omni_n1_compete_prime_2 <- omni_n1_means_prime_tab %>% 
  dplyr::filter(prime_cond == "competitor" & exp_cent == 36) %>% pull(report)
omni_n1_un_prime_1 <- omni_n1_means_prime_tab %>% 
  dplyr::filter(prime_cond == "unrelated" & exp_cent == -36) %>% pull(report)
omni_n1_un_prime_2 <- omni_n1_means_prime_tab %>% 
  dplyr::filter(prime_cond == "unrelated" & exp_cent == 36) %>% pull(report)
```

```{r erp_n1_3}
# Contrasts
omni_n1_means_prime_cont <- pairs(omni_n1_means_prime, by = "exp_cent", adj = "hommel") %>%
  data.frame()

# Pull pairwise contrasts
omni_n1_id_compete_prime_1 <- pair_comp(omni_n1_means_prime_cont %>% dplyr::filter(exp_cent == -36), "identity - competitor")
omni_n1_id_compete_prime_2 <- pair_comp(omni_n1_means_prime_cont %>% dplyr::filter(exp_cent == 36), "identity - competitor")
omni_n1_id_un_prime_1 <- pair_comp(omni_n1_means_prime_cont %>% dplyr::filter(exp_cent == -36), "identity - unrelated")
omni_n1_id_un_prime_2 <- pair_comp(omni_n1_means_prime_cont %>% dplyr::filter(exp_cent == 36), "identity - unrelated")
omni_n1_compete_un_prime_1 <- pair_comp(omni_n1_means_prime_cont %>% dplyr::filter(exp_cent == -36), "competitor - unrelated")
omni_n1_compete_un_prime_2 <- pair_comp(omni_n1_means_prime_cont %>% dplyr::filter(exp_cent == 36), "competitor - unrelated")

# Contrasts
omni_n1_means_exp_cont <- pairs(omni_n1_means_prime, by = "prime_cond", adj = "hommel") %>%
  data.frame() %>%
  rowwise() %>%
  mutate(z = stat_formatting(`z.ratio`),
         p = p_formatting(`p.value`),
         report = sprintf("*z* = %s, *p* %s", z, p))

# Pull
omni_n1_means_exp_cont_id <- omni_n1_means_exp_cont %>% 
  dplyr::filter(prime_cond == "identity") %>% pull(report)
omni_n1_means_exp_cont_compete <- omni_n1_means_exp_cont %>% 
  dplyr::filter(prime_cond == "competitor") %>% pull(report)
omni_n1_means_exp_cont_un <- omni_n1_means_exp_cont %>% 
  dplyr::filter(prime_cond == "unrelated") %>% pull(report)
```

```{r viz_n1_vot, include = FALSE, eval = FALSE}
vot_vals <- stim_full %>%
  dplyr::filter(stim_onset %in% c("p", "t", "k")) %>%
  mutate(stim_onset_fac = factor(stim_onset, 
                                 levels = c("p", "t", "k"),
                                 labels = c("/p/", "/t/", "/k/")))

vot_tab <- vot_vals %>%
  group_by(stim_onset) %>%
  summarise(q1 = quantile(vot, 0.25),
            q2 = quantile(vot, 0.50),
            q3 = quantile(vot, 0.75),
            q4 = quantile(vot, 1.00), 
            .groups = "keep")

erp_n1_vot <- erp_n1 %>%
  left_join(vot_tab) %>%
  mutate(vot_bin = case_when(
    vot <= q1 ~ "Q1",
    vot <= q2 ~ "Q2",
    vot <= q3 ~ "Q3",
    vot <= q4 ~ "Q4"
  ),
  prime_cond = factor(prime_cond, 
                      levels = c("identity", "competitor", "unrelated"),
                      labels = c("Identity", "Competitor", "Unrelated")),
  stim_onset_fac = factor(stim_onset, 
                                 levels = c("p", "t", "k"),
                                 labels = c("/p/", "/t/", "/k/")))
  
ggplot(erp_n1_vot, aes(x = exp_cent, y = volt, 
                       color = prime_cond,
                       fill = prime_cond)) +
  facet_grid(as.factor(vot_bin) ~ stim_onset_fac) +
  stat_smooth(method = "lm", formula = "y ~ x") +
  scale_color_manual(values = col_test, name = "Prime type") +
  scale_fill_manual(values = col_test, name = "Prime type") +
  scale_x_continuous(breaks = seq(-36, 36, 12)) +
  coord_cartesian(xlim = c(-36, 36)) +
  xlab("Amount of exposure (mean-centered)") +
  ylab("Mean amplitude (μV)") +
  theme_minimal() +
  theme(text = element_text(family = font_fam, size = text_size),
        axis.text.x = element_text(size = text_size*0.75),
        axis.ticks = element_blank(),
        legend.position = "bottom",
        legend.title = element_blank())

ggsave("outputs/vot_erp_plot.png",
       width = 3600, height = 2100, unit = "px", dpi = 300)

ggplot(vot_vals, aes(x = vot, color = stim_onset_fac)) +
  geom_density(linewidth = 1.5) + 
  scale_color_manual(values = c("#7fcdbb", "#41b6c4", "#2c7fb8")) +
  xlim(-20, 100) +
  ylim(0, 0.06) +
  ylab("Density") +
  xlab("VOT (ms)") +
  theme_minimal() +
  theme(text = element_text(family = font_fam, size = text_size),
        axis.text.x = element_text(size = text_size*0.75),
        axis.ticks = element_blank(),
        legend.position = "bottom",
        legend.title = element_blank())

ggsave("outputs/vot_plot.png",
       width = 3600, height = 2100, unit = "px", dpi = 300)
```

```{r omni_n1_vot}
# Run model
omni_n1_vot <- lmer(volt ~ vot_cent*exp_cent*prime_cond + freq_cent +
                  (1|target) + (1|id) + (1|chan),
                data = erp_n1)

# Model comparison
omni_n1_vot_comp <- Anova(omni_n1_vot, test = "Chi", type = "II")

# Means
omni_n1_vot_means <- emtrends(omni_n1_vot, c("vot_cent", "prime_cond"), "exp_cent")

# Pairwise comparisons
omni_n1_vot_cont <- omni_n1_vot_means %>% pairs(by = "prime_cond", adj = "hommel")
```

```{r omni_p2}
# Run model
omni_p2 <- lmer(volt ~ prime_cond*exp_cent + vot_cent + freq_cent +
                  (1|target) + (1|id) + (1|chan),
                data = erp_p2)

# Model comparison
omni_p2_comp <- Anova(omni_p2, test = "Chi", type = "II")

# Means
omni_p2_means <- emtrends(omni_p2, "prime_cond", "exp_cent")

# Pairwise comparisons
omni_p2_cont <- omni_p2_means %>% pairs(adj = "hommel")
```

```{r erp_p2_1}
# Pull model comparison stats
p2_comp_int <- mod_comp(omni_p2_comp, "prime_cond:exp_cent")
p2_comp_prime <- mod_comp(omni_p2_comp, "prime_cond")
p2_comp_exp <- mod_comp(omni_p2_comp, "exp_cent")

# Format means
omni_p2_means_tab <- omni_p2_means %>% 
  data.frame() %>%
  rowwise() %>%
  mutate(report = sprintf("*M* = %.3f, 95%% CI [%.3f, %.3f]", 
                          `exp_cent.trend`, `asymp.LCL`, `asymp.UCL`))

# Pull means
omni_p2_id <- omni_p2_means_tab %>% dplyr::filter(prime_cond == "identity") %>% pull(report)
omni_p2_compete <- omni_p2_means_tab %>% dplyr::filter(prime_cond == "competitor") %>% pull(report)
omni_p2_un <- omni_p2_means_tab %>% dplyr::filter(prime_cond == "unrelated") %>% pull(report)

# Pull pairwise contrasts
omni_p2_id_compete <- pair_comp(omni_p2_cont, "identity - competitor")
omni_p2_id_un <- pair_comp(omni_p2_cont, "identity - unrelated")
omni_p2_compete_un <- pair_comp(omni_p2_cont, "competitor - unrelated")
```

```{r erp_p2_2}
# Get means for prime
omni_p2_means_prime <- emmeans(omni_p2, ~ prime_cond*exp_cent, at = list(exp_cent = c(-36,36)))

# Format
omni_p2_means_prime_tab <- summary(omni_p2_means_prime) %>%
  mutate(report = sprintf("*M* = %.2f, 95%% CI [%.2f, %.2f]", 
                          emmean, `asymp.LCL`, `asymp.UCL`))

# Pull means
omni_p2_id_prime_1 <- omni_p2_means_prime_tab %>% 
  dplyr::filter(prime_cond == "identity" & exp_cent == -36) %>% pull(report)
omni_p2_id_prime_2 <- omni_p2_means_prime_tab %>% 
  dplyr::filter(prime_cond == "identity" & exp_cent == 36) %>% pull(report)
omni_p2_compete_prime_1 <- omni_p2_means_prime_tab %>% 
  dplyr::filter(prime_cond == "competitor" & exp_cent == -36) %>% pull(report)
omni_p2_compete_prime_2 <- omni_p2_means_prime_tab %>% 
  dplyr::filter(prime_cond == "competitor" & exp_cent == 36) %>% pull(report)
omni_p2_un_prime_1 <- omni_p2_means_prime_tab %>% 
  dplyr::filter(prime_cond == "unrelated" & exp_cent == -36) %>% pull(report)
omni_p2_un_prime_2 <- omni_p2_means_prime_tab %>% 
  dplyr::filter(prime_cond == "unrelated" & exp_cent == 36) %>% pull(report)
```

```{r erp_p2_3}
# Contrasts
omni_p2_means_prime_cont <- pairs(omni_p2_means_prime, by = "exp_cent", adj = "hommel") %>%
  data.frame()

# Pull pairwise contrasts
omni_p2_id_compete_prime_1 <- pair_comp(omni_p2_means_prime_cont %>% dplyr::filter(exp_cent == -36), "identity - competitor")
omni_p2_id_compete_prime_2 <- pair_comp(omni_p2_means_prime_cont %>% dplyr::filter(exp_cent == 36), "identity - competitor")
omni_p2_id_un_prime_1 <- pair_comp(omni_p2_means_prime_cont %>% dplyr::filter(exp_cent == -36), "identity - unrelated")
omni_p2_id_un_prime_2 <- pair_comp(omni_p2_means_prime_cont %>% dplyr::filter(exp_cent == 36), "identity - unrelated")
omni_p2_compete_un_prime_1 <- pair_comp(omni_p2_means_prime_cont %>% dplyr::filter(exp_cent == -36), "competitor - unrelated")
omni_p2_compete_un_prime_2 <- pair_comp(omni_p2_means_prime_cont %>% dplyr::filter(exp_cent == 36), "competitor - unrelated")

# Contrasts
omni_p2_means_exp_cont <- pairs(omni_p2_means_prime, by = "prime_cond", adj = "hommel") %>%
  data.frame() %>%
  rowwise() %>%
  mutate(z = stat_formatting(`z.ratio`),
         p = p_formatting(`p.value`),
         report = sprintf("*z* = %s, *p* %s", z, p))

# Pull
omni_p2_means_exp_cont_id <- omni_p2_means_exp_cont %>% dplyr::filter(prime_cond == "identity") %>% pull(report)
omni_p2_means_exp_cont_compete <- omni_p2_means_exp_cont %>% dplyr::filter(prime_cond == "competitor") %>% pull(report)
omni_p2_means_exp_cont_un <- omni_p2_means_exp_cont %>% dplyr::filter(prime_cond == "unrelated") %>% pull(report)
```

```{r omni_n400}
# Run model
omni_n4 <- lmer(volt ~ prime_cond*exp_cent + vot_cent + freq_cent +
                 (1|target) + (1|id) + (1|chan),
               data = erp_n4)

# Model comparison
omni_n4_comp <- Anova(omni_n4, test = "Chi", type = "II")

# Means
omni_n4_means <- emtrends(omni_n4, "prime_cond", "exp_cent")

# Pairwise comparisons
omni_n4_cont <- omni_n4_means %>% pairs(adj = "hommel")
```

```{r erp_n4_1}
# Pull model comparison stats
n4_comp_int <- mod_comp(omni_n4_comp, "prime_cond:exp_cent")
n4_comp_prime <- mod_comp(omni_n4_comp, "prime_cond")
n4_comp_exp <- mod_comp(omni_n4_comp, "exp_cent")

# Format means
omni_n4_means_tab <- omni_n4_means %>% 
  data.frame() %>%
  rowwise() %>%
  mutate(report = sprintf("*M* = %.3f, 95%% CI [%.3f, %.3f]", 
                          `exp_cent.trend`, `asymp.LCL`, `asymp.UCL`))

# Pull means
omni_n4_id <- omni_n4_means_tab %>% dplyr::filter(prime_cond == "identity") %>% pull(report)
omni_n4_compete <- omni_n4_means_tab %>% dplyr::filter(prime_cond == "competitor") %>% pull(report)
omni_n4_un <- omni_n4_means_tab %>% dplyr::filter(prime_cond == "unrelated") %>% pull(report)

# Pull pairwise contrasts
omni_n4_id_compete <- pair_comp(omni_n4_cont, "identity - competitor")
omni_n4_id_un <- pair_comp(omni_n4_cont, "identity - unrelated")
omni_n4_compete_un <- pair_comp(omni_n4_cont, "competitor - unrelated")
```

```{r erp_n4_2}
# Get means for prime
omni_n4_means_prime <- emmeans(omni_n4, ~ prime_cond*exp_cent, at = list(exp_cent = c(-36,36)))

# Format
omni_n4_means_prime_tab <- summary(omni_n4_means_prime) %>%
  mutate(report = sprintf("*M* = %.2f, 95%% CI [%.2f, %.2f]", 
                          emmean, `asymp.LCL`, `asymp.UCL`))

# Pull means
omni_n4_id_prime_1 <- omni_n4_means_prime_tab %>% 
  dplyr::filter(prime_cond == "identity" & exp_cent == -36) %>% pull(report)
omni_n4_id_prime_2 <- omni_n4_means_prime_tab %>% 
  dplyr::filter(prime_cond == "identity" & exp_cent == 36) %>% pull(report)
omni_n4_compete_prime_1 <- omni_n4_means_prime_tab %>% 
  dplyr::filter(prime_cond == "competitor" & exp_cent == -36) %>% pull(report)
omni_n4_compete_prime_2 <- omni_n4_means_prime_tab %>% 
  dplyr::filter(prime_cond == "competitor" & exp_cent == 36) %>% pull(report)
omni_n4_un_prime_1 <- omni_n4_means_prime_tab %>% 
  dplyr::filter(prime_cond == "unrelated" & exp_cent == -36) %>% pull(report)
omni_n4_un_prime_2 <- omni_n4_means_prime_tab %>% 
  dplyr::filter(prime_cond == "unrelated" & exp_cent == 36) %>% pull(report)
```

```{r erp_n4_3}
# Contrasts
omni_n4_means_prime_cont <- pairs(omni_n4_means_prime, by = "exp_cent", adj = "hommel") %>%
  data.frame()

# Pull pairwise contrasts
omni_n4_id_compete_prime_1 <- pair_comp(omni_n4_means_prime_cont %>% dplyr::filter(exp_cent == -36), "identity - competitor")
omni_n4_id_compete_prime_2 <- pair_comp(omni_n4_means_prime_cont %>% dplyr::filter(exp_cent == 36), "identity - competitor")
omni_n4_id_un_prime_1 <- pair_comp(omni_n4_means_prime_cont %>% dplyr::filter(exp_cent == -36), "identity - unrelated")
omni_n4_id_un_prime_2 <- pair_comp(omni_n4_means_prime_cont %>% dplyr::filter(exp_cent == 36), "identity - unrelated")
omni_n4_compete_un_prime_1 <- pair_comp(omni_n4_means_prime_cont %>% dplyr::filter(exp_cent == -36), "competitor - unrelated")
omni_n4_compete_un_prime_2 <- pair_comp(omni_n4_means_prime_cont %>% dplyr::filter(exp_cent == 36), "competitor - unrelated")

omni_n4_means_exp_cont <- pairs(omni_n4_means_prime, by = "prime_cond", adj = "hommel") %>%
  data.frame() %>%
  rowwise() %>%
  mutate(z = stat_formatting(`z.ratio`),
         p = p_formatting(`p.value`),
         report = sprintf("*z* = %s, *p* %s", z, p))

omni_n4_means_exp_cont_id <- omni_n4_means_exp_cont %>% dplyr::filter(prime_cond == "identity") %>% pull(report)
omni_n4_means_exp_cont_compete <- omni_n4_means_exp_cont %>% dplyr::filter(prime_cond == "competitor") %>% pull(report)
omni_n4_means_exp_cont_un <- omni_n4_means_exp_cont %>% dplyr::filter(prime_cond == "unrelated") %>% pull(report)
```

```{r erp_n1_plot}
y_breaks <- seq(-4.6, 2.4, 1)
y_lims <- c(-4.6, 2.4)

# Plot
erp_n1_dat <- emmip(omni_n1, prime_cond ~ exp_cent, 
                    CIs = TRUE, cov.reduce = range, plotit = FALSE) %>%
  mutate(prime_cond = factor(prime_cond, levels = c("identity", "competitor", "unrelated"),
                             labels = c("Identity", "Competitor", "Unrelated")))

erp_n1_plot <- ggplot(erp_n1_dat, aes(x = exp_cent, y = yvar, color = prime_cond)) +
  geom_line(size = 1.75) +
  geom_hline(yintercept = 0, linetype = "dashed") +
  scale_color_manual(values = col_test, name = "Prime type") +
  scale_x_continuous(breaks = seq(-36, 36, 12)) +
  scale_y_continuous(breaks = y_breaks) +
  coord_cartesian(xlim = c(-36, 36), ylim = y_lims) +
  xlab("Amount of exposure (mean-centered)") +
  ylab("Estimated marginal mean amplitude (μV)") +
  ggtitle("N1") +
  theme_minimal() +
  theme(legend.position = "bottom",
        text = element_text(family = font_fam, size = text_size),
        axis.ticks = element_blank(),
        plot.title = element_text(size = text_size, hjust = 0.5))
```

```{r erp_p2_plot}
# Plot
erp_p2_dat <- emmip(omni_p2, prime_cond ~ exp_cent, 
                    CIs = TRUE, cov.reduce = range, plotit = FALSE) %>%
  mutate(prime_cond = factor(prime_cond, levels = c("identity", "competitor", "unrelated"),
                             labels = c("Identity", "Competitor", "Unrelated")))

erp_p2_plot <- ggplot(erp_p2_dat, aes(x = exp_cent, y = yvar, color = prime_cond)) +
  geom_line(size = 1.75) +
  geom_hline(yintercept = 0, linetype = "dashed") +
  scale_color_manual(values = col_test, name = "Prime type") +
  scale_x_continuous(breaks = seq(-36, 36, 12)) +
  scale_y_continuous(breaks = y_breaks) +
  coord_cartesian(xlim = c(-36, 36), ylim = y_lims) +
  xlab("Amount of exposure (mean-centered)") +
  ylab("Estimated marginal mean amplitude (μV)") +
  ggtitle("P2") +
  theme_minimal() +
  theme(legend.position = "bottom",
        text = element_text(family = font_fam, size = text_size),
        axis.ticks = element_blank(),
        plot.title = element_text(size = text_size, hjust = 0.5))
```

```{r erp_n4_plot}
# Plot
erp_n4_dat <- emmip(omni_n4, prime_cond ~ exp_cent, 
                    CIs = TRUE, cov.reduce = range, plotit = FALSE) %>%
  mutate(prime_cond = factor(prime_cond, levels = c("identity", "competitor", "unrelated"),
                             labels = c("Identity", "Competitor", "Unrelated")))

erp_n4_plot <- ggplot(erp_n4_dat, aes(x = exp_cent, y = yvar, color = prime_cond)) +
  geom_line(size = 1.75) +
  geom_hline(yintercept = 0, linetype = "dashed") +
  scale_color_manual(values = col_test, name = "Prime type") +
  scale_x_continuous(breaks = seq(-36, 36, 12)) +
  scale_y_continuous(breaks = y_breaks) +
  coord_cartesian(xlim = c(-36, 36), ylim = y_lims) +
  xlab("Amount of exposure (mean-centered)") +
  ylab("Estimated marginal mean amplitude (μV)") +
  ggtitle("N400") +
  theme_minimal() +
  theme(legend.position = "bottom",
        text = element_text(family = font_fam, size = text_size),
        axis.ticks = element_blank(),
        plot.title = element_text(size = text_size, hjust = 0.5))
```

```{r erp_plots, include = FALSE}
erp_all_plot <- erp_n1_plot + erp_p2_plot + erp_n4_plot +
  plot_layout(axis_titles = "collect", guides = "collect") &
  theme(legend.position = "bottom")

# Save plot and crop to remove white space
ggsave("outputs/erp_eff.png", erp_all_plot,
       width = 4200, height = 2100, unit = "px", dpi = 300)
knitr::plot_crop("outputs/erp_eff.png")
```

```{r erp_corr_1}
# Run correlations
corr_list <- psych::corr.test(as.matrix(corr_dat),
                              adjust = "none",
                              use = "pairwise")

# Get r values
corr_r <- corr_list$r %>%
  data.frame() %>%
  rownames_to_column(var = "Var1") %>%
  pivot_longer(cols = c(everything(), -Var1),
               names_to = "Var2", values_to = "r") %>%
  dplyr::filter(r < 1)

# Get p values
corr_p <- corr_list$p %>%
  data.frame() %>%
  rownames_to_column(var = "Var1") %>%
  pivot_longer(cols = c(everything(), -Var1),
               names_to = "Var2", values_to = "p") %>%
  dplyr::filter(p > 0)

# Combine
corr_labs <- corr_p %>%
  left_join(corr_r, by = join_by(Var1, Var2)) %>%
  drop_na() %>%
  dplyr::filter(!duplicated(r))
```

```{r erp_corr_2}
# Get significant
corr_labs_sig <- corr_labs %>% dplyr::filter(p < .05)

# Only keep significant for plotting
corr_keep <- unique(c(corr_labs_sig$Var1, corr_labs_sig$Var2))
corr_dat_sub <- corr_dat %>% select(all_of(corr_keep))

# See kept columns
corr_keep

# # Make names
# corr_keep_name <- c("N1", "N400", "Reactive control", 
#                     "Receptive vocabulary", "Language attitudes", "Talker accent strength", 
#                     "Talker ease", "Talker comprehensibility", "Talker language accuracy", 
#                     "Talker region accuracy", "P2", "Proactive control",
#                     "Accent strength", "Bilingual identity", "Dialect history")
# 
# # "Talker English fluency"
# # "Behavioral accuracy"
# # "Talker accent accuracy"
# # "Caregiver language history"
# 
# # Rename
# colnames(corr_dat_sub) <- corr_keep_name
# 
# # Reorder
# corr_dat_sub <- corr_dat_sub %>%
#   select("N1", "P2", "N400", contains("control"), 
#          "Receptive vocabulary", "Language attitudes",
#          starts_with("Talker"), starts_with("Accent"), 
#          "Bilingual identity", "Dialect history")
```

```{r erp_corr_3}
corr_list_sub <-  psych::corr.test(as.matrix(corr_dat_sub),
                                  adjust = "none",
                                  use = "pairwise")

# Get r and p values
corr_r_simple <- corr_list_sub$r
corr_p_simple <- corr_list_sub$p
```

```{r erp_corr_4, include = FALSE}
# Make initial plot
corr_plot <- ggcorrplot::ggcorrplot(corr_r_simple, hc.order = FALSE, type = "upper", 
                                    outline.col = "#FFFFFF", lab = FALSE,
                                    ggtheme = ggplot2::theme_classic(), 
                                    colors = col_corr, p.mat = corr_p_simple,
                                    insig = "pch", pch.cex = 1, pch = 20, 
                                    pch.col = "#FFFFFF", show.legend = TRUE)

# Get asterisks                                             
corr_labs_simple <- corr_p_simple  %>%  
  as.data.frame() %>%
  mutate_all(labs_func) %>%
  rownames_to_column(var = "Var1") %>%
  pivot_longer(cols = c(everything(), -Var1), 
               names_to = "Var2", values_to = "lab") %>%
  right_join(corr_plot$data, by = c("Var1", "Var2"))

# Make plot
corr_plot_fin <- corr_plot +
  geom_text(aes(x = corr_labs_simple$Var1,
                y = corr_labs_simple$Var2),
            label = corr_labs_simple$lab,
            size = 3*1.5,
            color = "#000000") +
  scale_x_discrete(position = "top") +
  theme(axis.text.y = element_text(hjust = 1),
        axis.text.x = element_text(hjust = 0),
        text = element_text(family = font_fam, size = text_size),
        legend.title = element_blank(),
        legend.ticks = element_blank(),
        legend.position = "right",
        legend.key.height = unit(3, "lines"),
        legend.text = element_text(hjust = 1, size = text_size*0.5)) 

# Save plot and crop to remove white space
ggsave("outputs/corr_plot_2_v2.png", corr_plot_fin,
       width = 2400, height = 2100, unit = "px", dpi = 300)
knitr::plot_crop("outputs/corr_plot_2_v2.png")
```

```{r erp_corr_5}
# Get significant correlations
corr_labs_format <- apa_corr(corr_list) %>% 
  dplyr::filter(p < .05 & !duplicated(r))

# Format 1
corr_pro_n1 <- corr_labs_format %>% 
  dplyr::filter(Var1 == "proact" & Var2 == "mean_n1") %>% 
  pull(report)

# Format 2
corr_lex_comp <- corr_labs_format %>% 
  dplyr::filter(Var1 == "lextale_score" & Var2 == "spk_percep") %>% 
  pull(report)
```

```{r erp_corr_6, include = FALSE, eval = FALSE}
corr_dat_sub %>%
  select(`Proactive control`,`Reactive control`,`Receptive vocabulary`,
         `Language attitudes`, `Accent strength`) %>%
  pivot_longer(cols = everything(), names_to = "Measure", values_to = "vals") %>%
  drop_na() %>%
  group_by(Measure) %>%
  summarise(N = n(),
            M = sprintf("%.2f", mean(vals)),
            SD = sprintf("%.2f", sd(vals)),
            Range = sprintf("%.2f-%.2f", min(vals), max(vals))) %>%
  kable(format = "html", align = "l") %>%
  kable_styling(bootstrap_options = "striped", full_width = TRUE,
                font_size = 36) %>%
  save_kable(file = "demo_table.png")

corr_dat_sub %>%
  select(contains("Talker")) %>%
  pivot_longer(cols = everything(), names_to = "Measure", values_to = "vals") %>%
  drop_na() %>%
  group_by(Measure) %>%
  summarise(N = n(),
            M = sprintf("%.2f", mean(vals)),
            SD = sprintf("%.2f", sd(vals)),
            Range = sprintf("%.2f-%.2f", min(vals), max(vals))) %>%
  kable(format = "html", align = "l") %>%
  kable_styling(bootstrap_options = "striped", full_width = TRUE,
                font_size = 36) %>%
  save_kable(file = "talk_table.png")
```


