---
pagetitle: "general"
---

```{r exp_1b_1}
# Filter and factor
dat_exp_1b <- dat_exp_filt %>%
  dplyr::filter(version == "1b" & !is.na(vot)) %>%
  mutate(across(.cols = c("participant", "stim", "type",
                          "cond_sim", "cond_var"),
                as.factor),
         trial_cent = scale(trial)[,1],
         vot_cent = scale(vot)[,1],
         freq_cent = scale(FreqZipfUS)[,1])

# Add contrasts
contrasts(dat_exp_1b$cond_sim) <- contrast_sim
contrasts(dat_exp_1b$cond_var) <- contrast_var
contrasts(dat_exp_1b$type) <- contrast_type
```

```{r exp_1b_2}
# Run
exp_acc_1b <- glmer(resp_acc ~ cond_var*cond_sim*type + 
                      trial_cent + freq_cent + vot_cent +
                      (1|stim) + (cond_var*cond_sim|participant),
                    data = dat_exp_1b,
                    family = binomial,
                    control = glmerControl(optimizer = "bobyqa"))

# Model comparison
exp_acc_1b_comp <- Anova(exp_acc_1b, test = "Chi", type = "III")

# Format
exp_acc_1b_comp_3_form <- mod_comp(exp_acc_1b_comp, "cond_var:cond_sim:type")
exp_acc_1b_comp_2_form <- mod_comp(exp_acc_1b_comp, "cond_var:type")
```

```{r exp_1b_3a, message = FALSE, warning = FALSE}
# Means
exp_acc_1b_means <- emmeans(exp_acc_1b, ~ cond_sim*cond_var*type)

# Format
exp_acc_1b_means_form <- exp_acc_1b_means %>% 
  summary(type = "response") %>%
  left_join(tab_factor, by = c("cond_sim", "cond_var")) %>%
  left_join(tab_type, by = "type") %>%
  mutate(report = sprintf("*M* = %0.2f, 95%% CI [%0.2f, %0.2f]", 
                          prob, asymp.LCL, asymp.UCL))

# Contrasts by Variability
exp_acc_1b_cont_var <- pairs(exp_acc_1b_means, 
                             by = c("type", "cond_var"), 
                             adj = "hommel") %>%
  data.frame() %>%
  dplyr::filter(`p.value` <= .05) %>%
  left_join(tab_contrast_var, by = c("contrast", "cond_var")) %>% 
  mutate(cond_var_fac = factor(cond_var, levels = lev_var)) %>%
  left_join(tab_type, by = "type") %>%
  rowwise() %>%
  mutate(labs = labs_func(p.value))

# Contrasts by Similarity
exp_acc_1b_cont_sim <- pairs(exp_acc_1b_means, 
                             by = c("type", "cond_sim"), 
                             adj = "hommel") %>%
  data.frame() %>%
  dplyr::filter(`p.value` <= .05)
```

```{r exp_1b_3b}
# Variant - pseudo
exp_acc_1b_mean_non_dir_var <- exp_acc_1b_means_form %>%
  dplyr::filter(type == "nonword" & cond_exp_fac == "Direct-Variant") %>% 
  pull(report)
exp_acc_1b_mean_non_ind_var <- exp_acc_1b_means_form %>%
  dplyr::filter(type == "nonword" & cond_exp_fac == "Indirect-Variant") %>% 
  pull(report)
exp_acc_1b_cont_non_var <- exp_acc_1b_cont_var %>% pair_comp("direct - indirect")
```

```{r exp_1b_4}
# Filter and factor
dat_exp_1b_rt <- dat_exp_rt %>%
  dplyr::filter(version == "1b" & !is.na(vot)) %>%
  left_join(tab_factor, by = c("cond_var", "cond_sim")) %>%
  left_join(tab_type, by = c("type")) %>%
  mutate(across(.cols = c("participant", "stim", "type",
                          "cond_sim", "cond_var"),
                as.factor),
         trial_cent = scale(trial)[,1],
         vot_cent = scale(vot)[,1],
         freq_cent = scale(FreqZipfUS)[,1])

# Add contrasts
contrasts(dat_exp_1b_rt$cond_sim) <- contrast_sim
contrasts(dat_exp_1b_rt$cond_var) <- contrast_var
contrasts(dat_exp_1b_rt$type) <- contrast_type
```

```{r exp_1b_5}
# Run
exp_rt_1b <- lmer(inv_rt ~ cond_var*cond_sim*type + 
                       trial_cent + freq_cent + vot_cent +
                       (1|stim) + (1|participant),
                     data = dat_exp_1b_rt)

# Model comparison
exp_rt_1b_comp <- Anova(exp_rt_1b, test = "Chi", type = "III")

# Format
exp_rt_1b_comp_form <- mod_comp(exp_rt_1b_comp, "cond_var:type")
```

```{r exp_1b_6, message = FALSE, warning = FALSE}
# Means
exp_rt_1b_means_simple <- emmeans(exp_rt_1b, ~ cond_var*type)

# Contrasts
exp_rt_1b_cont_simple <- pairs(exp_rt_1b_means_simple, 
                               by = "type",
                               adjust = "hommel")

# Means
exp_rt_1b_means <- emmeans(exp_rt_1b, ~ cond_sim*cond_var*type)

# Format
exp_rt_1b_means_form <- exp_rt_1b_means %>%
  apa_rt() %>%
  left_join(tab_factor, by = c("cond_sim", "cond_var")) %>%
  left_join(tab_type, by = "type")

# Contrasts by Variability
exp_rt_1b_cont_var <- pairs(exp_rt_1b_means, 
                             by = c("type", "cond_var"), 
                             adj = "hommel") %>%
  data.frame() %>%
  dplyr::filter(`p.value` <= .05)

# Contrasts by Similarity
exp_rt_1b_cont_sim <- pairs(exp_rt_1b_means, 
                             by = c("type", "cond_sim"), 
                             adj = "hommel") %>%
  data.frame() %>%
  dplyr::filter(`p.value` <= .05)
```

```{r exp_1b_7}
# Get average accuracy
dat_exp_1b_acc <- dat_exp_1b %>%
  group_by(participant, cond_var, cond_sim, cond_exp, type) %>% 
  summarise(mean_acc = mean(resp_acc), .groups = "keep") %>%
  left_join(tab_factor, by = c("cond_var", "cond_sim")) %>%
  left_join(tab_type, by = c("type"))

# Get average RT
dat_exp_1b_sum <- dat_exp_1b_rt %>%
  group_by(participant, cond_var, cond_sim, cond_exp, type) %>% 
  summarise(mean_rt = mean(real_rt), .groups = "keep") %>%
  left_join(dat_exp_1b_acc,
            by = join_by(participant, cond_var, cond_sim, cond_exp, type))
```

```{r exp_1b_8, include = FALSE}
# Plot
plot_exp_1b_acc_var <- ggplot() +
  geom_boxplot(data = dat_exp_1b_acc, 
               aes(x = cond_var_fac, y = mean_acc, 
                   color = cond_exp_fac, fill = cond_exp_fac),
               size = g_line, alpha = alpha_lev) +
  geom_point(data = exp_acc_1b_means_form,
             aes(x = cond_var_fac, y = prob, group = cond_sim_fac), 
             position = position_dodge(width = g_dodge),
             color = "black", size = g_point*1.25) +
  geom_errorbar(data = exp_acc_1b_means_form,
             aes(x = cond_var_fac, group = cond_sim_fac,
                 ymin = `asymp.LCL`, ymax = `asymp.UCL`), 
             position = position_dodge(width = g_dodge),
             color = "black", width = 0.25, size = g_line) +
  facet_grid(~ type_fac) + 
  geom_segment(data = exp_acc_1b_cont_var,
               aes(x = x, xend = xend, y = 1)) +
  geom_text(data = exp_acc_1b_cont_var,
            aes(x = lab_pos, y = 1.01, label = labs),
            fontface = "bold", size = sig_size) +
  scale_color_manual(values = col_exp, name = "Exposure condition") +
  scale_fill_manual(values = col_exp, name = "Exposure condition") +
  xlab("Variability") +
  ylab("Accuracy") +
  scale_y_continuous(breaks = acc_seq) +
  coord_cartesian(ylim = acc_range) +
  theme_minimal() +
  theme(text = element_text(family = font_fam, size = text_size)) +
  guides(color = "none", fill = "none")
  
# Plot
plot_exp_1b_acc_sim <- ggplot() +
  geom_boxplot(data = dat_exp_1b_acc, 
               aes(x = cond_sim_fac, y = mean_acc, 
                   color = cond_exp_fac, fill = cond_exp_fac),
               size = g_line, alpha = alpha_lev) +
  geom_point(data = exp_acc_1b_means_form,
             aes(x = cond_sim_fac, y = prob, group = cond_var_fac), 
             position = position_dodge(width = g_dodge),
             color = "black", size = g_point*1.25) +
  geom_errorbar(data = exp_acc_1b_means_form,
             aes(x = cond_sim_fac, group = cond_var_fac,
                 ymin = `asymp.LCL`, ymax = `asymp.UCL`), 
             position = position_dodge(width = g_dodge),
             color = "black", width = 0.25, size = g_line) +
  facet_grid(~ type_fac) + 
  scale_color_manual(values = col_exp, name = "Exposure condition") +
  scale_fill_manual(values = col_exp, name = "Exposure condition") +
  xlab("Similarity") +
  ylab("Accuracy") +
  scale_y_continuous(breaks = acc_seq) +
  coord_cartesian(ylim = acc_range) +
  theme_minimal() +
  theme(text = element_text(family = font_fam, size = text_size))  +
  guides(color = "none", fill = "none")
```

```{r exp_1b_9, include = FALSE}
# Plot
plot_exp_1b_rt_var <- ggplot() +
  geom_half_violin(data = dat_exp_1b_rt, 
                   aes(x = cond_var_fac, y = real_rt, 
                       color = cond_exp_fac, fill = cond_exp_fac),
                   scale = "count", alpha = alpha_lev) + 
  geom_half_point(data = dat_exp_1b_sum,
                  aes(x = cond_var_fac, y = mean_rt, color = cond_exp_fac),
                  alpha = alpha_lev) +
  geom_point(data = exp_rt_1b_means_form,
             aes(x = cond_var_fac, y = rt, group = cond_sim_fac),
             position = position_dodge(width = g_dodge),
             color = "black", size = g_point*1.25) + 
  geom_errorbar(data = exp_rt_1b_means_form,
                aes(x = cond_var_fac, group = cond_sim_fac,
                    ymin = rt_low, ymax = rt_high), 
                position = position_dodge(width = g_dodge),
                color = "black", width = 0.25, size = g_line) +
  facet_grid(~ type_fac) + 
  scale_color_manual(values = col_exp, name = "Exposure condition") +
  scale_fill_manual(values = col_exp, name = "Exposure condition") +
  xlab("Variability") +
  ylab("Reaction time (ms)") +
  scale_y_continuous(breaks = seq(750, 2550, 300)) +
  coord_cartesian(ylim = c(740, 2560)) +
  theme_minimal() +
  theme(text = element_text(family = font_fam, size = text_size))  +
  guides(color = "none")
  
# Plot
plot_exp_1b_rt_sim <- ggplot() +
  geom_half_violin(data = dat_exp_1b_rt, 
                   aes(x = cond_sim_fac, y = real_rt, 
                       color = cond_exp_fac, fill = cond_exp_fac),
                   scale = "count", alpha = alpha_lev) + 
  geom_half_point(data = dat_exp_1b_sum,
                  aes(x = cond_sim_fac, y = mean_rt, color = cond_exp_fac),
                  alpha = alpha_lev) +
  geom_point(data = exp_rt_1b_means_form,
             aes(x = cond_sim_fac, y = rt, group = cond_var_fac),
             position = position_dodge(width = g_dodge),
             color = "black", size = g_point*1.25) + 
  geom_errorbar(data = exp_rt_1b_means_form,
                aes(x = cond_sim_fac, group = cond_var_fac,
                    ymin = rt_low, ymax = rt_high), 
                position = position_dodge(width = g_dodge),
                color = "black", width = 0.25, size = g_line) +
  facet_grid(~ type_fac) + 
  scale_color_manual(values = col_exp, name = "Exposure condition") +
  scale_fill_manual(values = col_exp, name = "Exposure condition") +
  xlab("Similarity") +
  ylab("Reaction time (ms)") +
  scale_y_continuous(breaks = seq(750, 2550, 300)) +
  coord_cartesian(ylim = c(740, 2560)) +
  theme_minimal() +
  theme(text = element_text(family = font_fam, size = text_size)) +
  guides(color = "none")
```

```{r exp_1b_9_save_plot, include = FALSE}
plot_exp_1b <- plot_exp_1b_acc_var + plot_exp_1b_rt_var + 
  plot_exp_1b_acc_sim + plot_exp_1b_rt_sim +
  plot_layout(nrow = 2, axes = "collect_y", guides = "collect") &
  theme(legend.position = "bottom")

# Save plot and crop to remove white space
ggsave("outputs/plot_exp_1b.png", plot_exp_1b,
       width = 5600, height = 4200, unit = "px", dpi = 300)
knitr::plot_crop("outputs/plot_exp_1b.png")
```

```{r test_1b_1}
# Filter and factor
dat_test_1b <- dat_test_filt %>%
  dplyr::filter(version %in% c("1b", "1c")) %>%
  mutate(across(.cols = c("participant", "prime", "target", "match_type"),
                as.factor),
         trial_cent = scale(trial)[,1],
         vot_cent = scale(vot)[,1],
         freq_prime_cent = scale(FreqZipfUS_prime)[,1],
         freq_target_cent = scale(FreqZipfUS_target)[,1]) %>%
  left_join(tab_exp, by = "cond_exp")

# Add contrasts
contrasts(dat_test_1b$cond_exp_fac) <- contrast_train
contrasts(dat_test_1b$match_type) <- contrast_match_1
```

```{r test_1b_2}
# Run
test_acc_1b_train <- glmer(resp_acc ~ cond_exp_fac*match_type + 
                       trial_cent + freq_prime_cent:freq_target_cent + 
                         vot_cent +
                       (1|prime:target) + (1|participant),
                     data = dat_test_1b,
                     family = binomial,
                     control = glmerControl(optimizer = "bobyqa"))

# Model comparison
test_acc_1b_train_comp <- Anova(test_acc_1b_train, test = "Chi", type = "III")

# Format
test_acc_1b_comp_form <- mod_comp(test_acc_1b_train_comp, "cond_exp_fac:match_type")
```

```{r test_1b_3a}
# Get means
test_acc_1b_train_means <- emmeans(test_acc_1b_train, ~ cond_exp_fac*match_type)

# Format
test_acc_1b_train_means_form <- test_acc_1b_train_means %>%
  summary(type = "response") %>%
  left_join(tab_exp, by = "cond_exp_fac") %>%
  left_join(tab_match, by = "match_type") %>%
  mutate(report = sprintf("*M* = %.2f, 95%% CI [%.2f, %.2f]", 
                          prob, asymp.LCL, asymp.UCL))

# Select contrasts
test_acc_1b_train_coef <- emmeans:::pairwise.emmc(levels(test_acc_1b_train_means)$cond_exp_fac)
test_acc_1b_train_coef_1 <- test_acc_1b_train_coef[c(1:4)]
test_acc_1b_train_coef_2 <- test_acc_1b_train_coef[c(5:10)]

# Run contrasts
test_acc_1b_train_cont_1 <- contrast(test_acc_1b_train_means, 
                                   test_acc_1b_train_coef_1, 
                                   by = "match_type",
                                   adj = "hommel")
test_acc_1b_train_cont_2 <- contrast(test_acc_1b_train_means, 
                                   test_acc_1b_train_coef_2, 
                                   by = "match_type",
                                   adj = "hommel") %>%
  data.frame() %>%
  dplyr::filter(`p.value` <= .05) %>%
  left_join(tab_match, by = "match_type") %>%
  left_join(tab_contrast_exp, by = join_by(contrast, match_type)) %>%
  rowwise() %>%
  mutate(labs = labs_func(p.value))
```

```{r test_1b_3b}
# Competitor
test_acc_1b_comp_dir_var <- test_acc_1b_train_means_form %>% 
  dplyr::filter(match_type == "competitor" & cond_exp_fac == "Direct-Variant") %>%
  pull(report)
test_acc_1b_comp_dir_invar <- test_acc_1b_train_means_form %>% 
  dplyr::filter(match_type == "competitor" & cond_exp_fac == "Direct-Invariant") %>%
  pull(report)
test_acc_1b_comp_indir_var <- test_acc_1b_train_means_form %>% 
  dplyr::filter(match_type == "competitor" & cond_exp_fac == "Indirect-Variant") %>%
  pull(report)
test_acc_1b_comp_indir_invar <- test_acc_1b_train_means_form %>% 
  dplyr::filter(match_type == "competitor" & cond_exp_fac == "Indirect-Invariant") %>%
  pull(report)
test_acc_1b_comp_dir_varinvar <- pair_comp(test_acc_1b_train_cont_2, 
                                           "Direct-Variant - Direct-Invariant")
test_acc_1b_comp_invar_dirindir <- pair_comp(test_acc_1b_train_cont_2, 
                                           "Direct-Invariant - Indirect-Invariant")
test_acc_1b_comp_dirinvar_indirinvar <- pair_comp(test_acc_1b_train_cont_2, 
                                           "Direct-Invariant - Indirect-Variant")
```

```{r test_1b_4}
# Filter and factor
dat_test_1b_rt <- dat_test_rt %>%
  dplyr::filter(version %in% c("1b", "1c")) %>%
  mutate(across(.cols = c("participant", "prime", "target", "match_type"),
                as.factor),
         trial_cent = scale(trial)[,1],
         vot_cent = scale(vot)[,1],
         freq_prime_cent = scale(FreqZipfUS_prime)[,1],
         freq_target_cent = scale(FreqZipfUS_target)[,1]) %>%
  left_join(tab_exp, by = "cond_exp")

# Add contrasts
contrasts(dat_test_1b_rt$cond_exp_fac) <- contrast_train
contrasts(dat_test_1b_rt$match_type) <- contrast_match_1
```

```{r test_1b_5}
# Run
test_rt_1b_train <- lmer(inv_rt ~ cond_exp_fac*match_type + 
                           trial_cent + freq_prime_cent:freq_target_cent + 
                           vot_cent +
                       (1|prime:target) + (1|participant),
                     data = dat_test_1b_rt)

# Model comparison
test_rt_1b_train_comp <- Anova(test_rt_1b_train, test = "Chi", type = "III")

# Format
test_rt_1b_comp_form <- mod_comp(test_rt_1b_train_comp, "cond_exp_fac:match_type")
```

```{r test_1b_6a, warning = FALSE, message = FALSE}
# Get means
test_rt_1b_train_means <- emmeans(test_rt_1b_train, 
                                  ~ cond_exp_fac*match_type)

# Select contrasts
test_rt_1b_train_coef <- emmeans:::pairwise.emmc(levels(test_rt_1b_train_means)$cond_exp_fac)
test_rt_1b_train_coef_1 <- test_rt_1b_train_coef[c(1:4)]
test_rt_1b_train_coef_2 <- test_rt_1b_train_coef[c(5:10)]

# Run contrasts
test_rt_1b_train_cont_1 <- contrast(test_rt_1b_train_means, 
                                   test_rt_1b_train_coef_1, 
                                   by = "match_type",
                                   adj = "hommel")
test_rt_1b_train_cont_2 <- contrast(test_rt_1b_train_means, 
                                   test_rt_1b_train_coef_2, 
                                   by = "match_type",
                                   adj = "hommel") %>%
  data.frame() %>%
  dplyr::filter(`p.value` <= .05)

# Format
test_rt_1b_train_means_form <- test_rt_1b_train_means %>%
  apa_rt() %>%
  left_join(tab_exp, by = "cond_exp_fac") %>%
  left_join(tab_match, by = "match_type")
```

```{r test_1b_6b}
# Identity
test_rt_1b_id_dir_invar <- test_acc_1b_train_means_form %>% 
  dplyr::filter(match_type == "identity" & cond_exp_fac == "Direct-Invariant") %>%
  pull(report)
test_rt_1b_id_indir_var <- test_acc_1b_train_means_form %>% 
  dplyr::filter(match_type == "identity" & cond_exp_fac == "Indirect-Variant") %>%
  pull(report)
test_rt_1b_comp_dirinvar_indirvar <- pair_comp(test_rt_1b_train_cont_2, 
                                               "Direct-Invariant - Indirect-Variant")
```

```{r test_1b_7}
# Get average accuracy
dat_test_1b_acc <- dat_test_1b %>%
  group_by(participant, cond_exp, match_type) %>% 
  summarise(mean_acc = mean(resp_acc), .groups = "keep") %>%
  left_join(tab_exp, by = "cond_exp") %>%
  left_join(tab_match, by = "match_type")
```

```{r test_1b_8, include = FALSE}
# Plot
plot_test_1b_acc <- ggplot() +
  geom_boxplot(data = dat_test_1b_acc, 
               aes(x = cond_exp_fac, y = mean_acc,
                   color = cond_exp_fac, 
                   fill = cond_exp_fac),
               size = g_line*1.25, alpha = alpha_lev,
               outlier.size = g_point*1.25) +
  geom_point(data = test_acc_1b_train_means_form,
             aes(x = cond_exp_fac, y = prob, 
                 group = match_type_fac), 
             position = position_dodge(width = g_dodge),
             color = "black", size = g_point*1.5) +
  geom_errorbar(data = test_acc_1b_train_means_form,
             aes(x = cond_exp_fac, group = match_type_fac,
                 ymin = `asymp.LCL`, ymax = `asymp.UCL`), 
             position = position_dodge(width = g_dodge),
             color = "black", width = 0.25, size = g_line) +
  facet_grid(~ match_type_fac) +
  scale_color_manual(values = c("#A8A8A8", col_exp), name = "Exposure condition") +
  scale_fill_manual(values = c("#A8A8A8", col_exp), name = "Exposure condition") +
  xlab("Exposure condition") +
  ylab("Accuracy") +
  scale_y_continuous(breaks = seq(0, 1, 0.2)) +
  scale_x_discrete(guide = guide_axis(angle = 45)) +
  coord_cartesian(ylim = c(0, 1.01)) +
  theme_minimal() +
  theme(text = element_text(family = font_fam, size = text_size)) +
  guides(color = "none", fill = "none")
```

```{r test_1b_8_save_plot, include = FALSE}
# Save plot and crop to remove white space
ggsave("outputs/plot_test_1b.png", plot_test_1b_acc,
       width = 5600, height = 2800, unit = "px", dpi = 300)
knitr::plot_crop("outputs/plot_test_1b.png")
```

